[ACC] some makefile and install script changes
Contributor: Xiaonan Tian

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -273,6 +273,7 @@ PACKAGE_BUGREPORT=''
 
 ac_subdirs_all="$ac_subdirs_all osprey/cygnus"
 ac_subdirs_all="$ac_subdirs_all osprey-gcc-4.2.0"
+
 ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os uh_config_arguments BASH_PATH MPICC_PATH MACHINE_TYPE CROSS_TARGET BUILD_ABI BUILD_ARCH BUILD_HOST BUILD_TARGET BUILD_VENDOR BUILD_OPTIMIZE BUILD_FFE_OPTIMIZE BUILD_LIB_OPTIMIZE BUILD_COMPILER BUILD_BOTH LIB_MACHINE_TYPE LIB_BUILD_TARGET LIB_BUILD_ABI LIB_BUILD_ARCH LIB_BUILD_HOST LIB2_MACHINE_TYPE LIB2_BUILD_TARGET LIB2_BUILD_ABI LIB2_BUILD_ARCH LIB2_BUILD_HOST BUILD_MULTILIB COMPILER_TARG_DIR TARG_INFO_NAME BUILD_GNU3 BUILD_FORTRAN WHIRL_HAS_ID_FIELD BUILD_SKIP_IPA BUILD_TYPE DRAGON_SUPPORT GCC_CONFIGURE_TARG GCC_DIR BUILD_GNU4 ENABLE_COARRAYS BUILD_CAF_RUNTIME DEFAULT_CAF_HEAP_SIZE DEFAULT_CAF_TEAMS_HEAP_SIZE GASNET_HOME GASNET_CONDUITS SHMEM_HOME SHMEM_LDFLAGS ARMCI_HOME ARMCI_NETWORK_LIBS CAFRT_ENABLE_DTRACES CAFRT_ENABLE_PROFILES DEFAULT_COMM UHCAF_MPI_INCLUDE UHCAF_MPI_FCFLAGS UHCAF_MPI_LDFLAGS BUILD_LIBUHINSTR TAU_ROOT TAU_LIBS EPIK_ROOT OPENUH_VERSION ENABLE_OSA CUDA_HOME AMD_CL_HOME INTEL_CL_HOME LIBLIST subdirs LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
@@ -835,10 +836,8 @@ Optional Packages:
                           kilobytes,megabytes,gigabytes respectively. Will be
                           10M if unspecified.
   --with-cuda=<cuda path> CUDA path for building libopenacc
-  --with-opencl-amd=<opencl path>
-                          AMD OpenCL path for building libopenacc_amd
-  --with-opencl-intel=<opencl path>
-                          INTEL OpenCL path for building libopenacc_intel
+  --with-amd-hsa=<hsa library path>
+                          AMD HSA library path for building libopenacc_amd
   --with-build-optimize=DEFAULT|DEBUG	Use DEFAULT or DEBUG flags in compiler build
   --with-build-ffe-optimize=DEFAULT|DEBUG Use DEFAULT or DEBUG flags in FFE build
   --with-build-lib-optimize=DEFAULT|DEBUG Use DEFAULT or DEBUG flags in library build.
@@ -1448,6 +1447,7 @@ if test "$build_alias" = "" && test "$target_alias" = "" && test "$target_cpu" =
   target_cpu=i686
   target=$target_cpu-$target_vendor-$target_os
 fi
+ACC_TARGET=
 
 
 # Check whether --with-build-compiler or --without-build-compiler was given.
@@ -1602,23 +1602,14 @@ else
   CUDA_HOME=""
 fi;
 
-#opencl
+#hsa
 
-# Check whether --with-opencl_amd or --without-opencl_amd was given.
-if test "${with_opencl_amd+set}" = set; then
-  withval="$with_opencl_amd"
-  AMD_CL_HOME="$with_opencl_amd"
+# Check whether --with-amd_hsa or --without-amd_hsa was given.
+if test "${with_amd_hsa+set}" = set; then
+  withval="$with_amd_hsa"
+  AMD_HSA_HOME="$with_amd_hsa"
 else
-  AMD_CL_HOME=""
-fi;
-
-
-# Check whether --with-opencl_intel or --without-opencl_intel was given.
-if test "${with_opencl_intel+set}" = set; then
-  withval="$with_opencl_intel"
-  INTEL_CL_HOME="$with_opencl_intel"
-else
-  INTEL_CL_HOME=""
+  AMD_HSA_HOME=""
 fi;
 
 # set bash path
@@ -1808,17 +1799,22 @@ if test -n "${CUDA_HOME}"; then
       { { echo "$as_me:$LINENO: error: Specified --with-cuda=<path> does not look right. Check path." >&5
 echo "$as_me: error: Specified --with-cuda=<path> does not look right. Check path." >&2;}
    { (exit 1); exit 1; }; }
+  else
+      ACC_TARGET="NVIDIA"
   fi
 fi
 
-if test -n "${AMD_CL_HOME}"; then
-  if test ! -d "${AMD_CL_HOME}"; then
-      { { echo "$as_me:$LINENO: error: Specified --with-opencl-amd=<path> does not look right. Check path." >&5
-echo "$as_me: error: Specified --with-opencl-amd=<path> does not look right. Check path." >&2;}
+if test -n "${AMD_HSA_HOME}"; then
+  if test ! -d "${AMD_HSA_HOME}"; then
+      { { echo "$as_me:$LINENO: error: Specified --with-amd-hsa=<path> does not look right. Check path." >&5
+echo "$as_me: error: Specified --with-amd-hsa=<path> does not look right. Check path." >&2;}
    { (exit 1); exit 1; }; }
+  else
+      ACC_TARGET="AMDAPU"
   fi
 fi
 
+<<<<<<< HEAD
 if test -n "${INTEL_CL_HOME}"; then
   if test ! -d "${INTEL_CL_HOME}"; then
        { { echo "$as_me:$LINENO: error: Specified --with-opencl-intel=<path> does not look right. Check path." >&5
@@ -1841,6 +1837,8 @@ echo "$as_me: error: --with-shmem-root=<path> must be specified if you want to u
    { (exit 1); exit 1; }; }
 fi
 
+=======
+>>>>>>> temporary version of install script
 if test -z "${DEFAULT_COMM}" -a -n "${GASNET_HOME}"; then
   DEFAULT_COMM=gasnet
 elif test -z "${DEFAULT_COMM}" -a -n "${ARMCI_HOME}" ; then
@@ -2484,10 +2482,7 @@ elif test "${BUILD_TARGET}" = "IA64"; then
   if test -n "${CUDA_HOME}"; then
     LIBLIST="$LIBLIST libopenacc"
   fi
-  if test -n "${INTEL_CL_HOME}"; then
-    LIBLIST="$LIBLIST libopenacc_intel"
-  fi
-  if test -n "${AMD_CL_HOME}"; then
+  if test -n "${AMD_HSA_HOME}"; then
     LIBLIST="$LIBLIST libopenacc_amd"
   fi
   if test "${BUILD_FORTRAN}" = "YES"; then
@@ -2504,10 +2499,7 @@ else
   if test -n "${CUDA_HOME}"; then
        LIBLIST="$LIBLIST libopenacc"
   fi
-  if test -n "${INTEL_CL_HOME}"; then
-       LIBLIST="$LIBLIST libopenacc_intel"
-  fi
-  if test -n "${AMD_CL_HOME}"; then
+  if test -n "${AMD_HSA_HOME}"; then
        LIBLIST="$LIBLIST libopenacc_amd"
   fi
   if test "${BUILD_FORTRAN}" = "YES"; then
@@ -2532,11 +2524,7 @@ if test -n "${CUDA_HOME}"; then
              ac_config_files="$ac_config_files osprey/targdir_lib/libopenacc/Makefile"
 
 fi
-if test -n "${INTEL_CL_HOME}"; then
-             ac_config_files="$ac_config_files osprey/targdir_lib/libopenacc_intel/Makefile"
-
-fi
-if test -n "${AMD_CL_HOME}"; then
+if test -n "${AMD_HSA_HOME}"; then
              ac_config_files="$ac_config_files osprey/targdir_lib/libopenacc_amd/Makefile"
 
 fi
@@ -2580,11 +2568,7 @@ if test $BUILD_MULTILIB = "YES"; then
 	            ac_config_files="$ac_config_files osprey/targdir_lib2/libopenacc/Makefile:osprey/targdir_lib/libopenacc/Makefile.in"
 
   fi
-  if test -n "${INTEL_CL_HOME}"; then
-	            ac_config_files="$ac_config_files osprey/targdir_lib2/libopenacc_intel/Makefile:osprey/targdir_lib/libopenacc_intel/Makefile.in"
-
-  fi
-  if test -n "${AMD_CL_HOME}"; then
+  if test -n "${AMD_HSA_HOME}"; then
 	            ac_config_files="$ac_config_files osprey/targdir_lib2/libopenacc_amd/Makefile:osprey/targdir_lib/libopenacc_amd/Makefile.in"
 
   fi
@@ -3227,7 +3211,6 @@ do
   "osprey/targdir_lib/include/Makefile" ) CONFIG_FILES="$CONFIG_FILES osprey/targdir_lib/include/Makefile" ;;
   "osprey/targdir_lib/libinstr/Makefile" ) CONFIG_FILES="$CONFIG_FILES osprey/targdir_lib/libinstr/Makefile:osprey/targdir_lib/libinstr2/Makefile.in" ;;
   "osprey/targdir_lib/libopenacc/Makefile" ) CONFIG_FILES="$CONFIG_FILES osprey/targdir_lib/libopenacc/Makefile" ;;
-  "osprey/targdir_lib/libopenacc_intel/Makefile" ) CONFIG_FILES="$CONFIG_FILES osprey/targdir_lib/libopenacc_intel/Makefile" ;;
   "osprey/targdir_lib/libopenacc_amd/Makefile" ) CONFIG_FILES="$CONFIG_FILES osprey/targdir_lib/libopenacc_amd/Makefile" ;;
   "osprey/targdir_lib/libopenmp/Makefile" ) CONFIG_FILES="$CONFIG_FILES osprey/targdir_lib/libopenmp/Makefile" ;;
   "osprey/targdir_lib/libopenmp-pcl/Makefile" ) CONFIG_FILES="$CONFIG_FILES osprey/targdir_lib/libopenmp-pcl/Makefile" ;;
@@ -3247,7 +3230,6 @@ do
   "osprey/targdir_lib/init/Makefile" ) CONFIG_FILES="$CONFIG_FILES osprey/targdir_lib/init/Makefile:osprey/targdir_lib/init/Makefile.in" ;;
   "osprey/targdir_lib/libuhinstr/Makefile" ) CONFIG_FILES="$CONFIG_FILES osprey/targdir_lib/libuhinstr/Makefile" ;;
   "osprey/targdir_lib2/libopenacc/Makefile" ) CONFIG_FILES="$CONFIG_FILES osprey/targdir_lib2/libopenacc/Makefile:osprey/targdir_lib/libopenacc/Makefile.in" ;;
-  "osprey/targdir_lib2/libopenacc_intel/Makefile" ) CONFIG_FILES="$CONFIG_FILES osprey/targdir_lib2/libopenacc_intel/Makefile:osprey/targdir_lib/libopenacc_intel/Makefile.in" ;;
   "osprey/targdir_lib2/libopenacc_amd/Makefile" ) CONFIG_FILES="$CONFIG_FILES osprey/targdir_lib2/libopenacc_amd/Makefile:osprey/targdir_lib/libopenacc_amd/Makefile.in" ;;
   "osprey/targdir_lib2/Makefile" ) CONFIG_FILES="$CONFIG_FILES osprey/targdir_lib2/Makefile:osprey/targdir_lib/Makefile.in" ;;
   "osprey/targdir_lib2/include/Makefile" ) CONFIG_FILES="$CONFIG_FILES osprey/targdir_lib2/include/Makefile:osprey/targdir_lib/include/Makefile.in" ;;
@@ -3422,8 +3404,8 @@ s,@EPIK_ROOT@,$EPIK_ROOT,;t t
 s,@OPENUH_VERSION@,$OPENUH_VERSION,;t t
 s,@ENABLE_OSA@,$ENABLE_OSA,;t t
 s,@CUDA_HOME@,$CUDA_HOME,;t t
-s,@AMD_CL_HOME@,$AMD_CL_HOME,;t t
-s,@INTEL_CL_HOME@,$INTEL_CL_HOME,;t t
+s,@AMD_HSA_HOME@,$AMD_HSA_HOME,;t t
+s,@ACC_TARGET@,$ACC_TARGET,;t t
 s,@LIBLIST@,$LIBLIST,;t t
 s,@subdirs@,$subdirs,;t t
 s,@LIBOBJS@,$LIBOBJS,;t t
@@ -3969,10 +3951,10 @@ fi
 echo "$as_me:    ENABLE_OSA                     = $ENABLE_OSA" >&6;}
 { echo "$as_me:$LINENO:    CUDA_HOME                      = $CUDA_HOME" >&5
 echo "$as_me:    CUDA_HOME                      = $CUDA_HOME" >&6;}
-{ echo "$as_me:$LINENO:    AMD_CL_HOME                    = $AMD_CL_HOME" >&5
-echo "$as_me:    AMD_CL_HOME                    = $AMD_CL_HOME" >&6;}
-{ echo "$as_me:$LINENO:    INTEL_CL_HOME                  = $INTEL_CL_HOME" >&5
-echo "$as_me:    INTEL_CL_HOME                  = $INTEL_CL_HOME" >&6;}
+{ echo "$as_me:$LINENO:    AMD_HSA_HOME                    = $AMD_HSA_HOME" >&5
+echo "$as_me:    AMD_HSA_HOME                    = $AMD_HSA_HOME" >&6;}
+{ echo "$as_me:$LINENO:    ACC_TARGET                    = $ACC_TARGET" >&5
+echo "$as_me:    ACC_TARGET                    = $ACC_TARGET" >&6;}
 { echo "$as_me:$LINENO: " >&5
 echo "$as_me: " >&6;}
 { echo "$as_me:$LINENO: ********************************************************************" >&5
