[CAF] Adds some new scripts for uhcaf/cafrun
Adds new scripts and some improvements for configuration and installing. The
runtime build process will create runtime for various GASNet conduits that are
available. This adds a -link-gcpp flag will instructs the driver to use g++ as
the linker, and this is used to upport the GASNet udp conduit.

Note: gasnet-udp conduit will not work if IPA is enabled (CAF compilation will
fail).

Contributor: Deepak

git-svn-id: https://svn.open64.net/svnroot/open64/branches/OpenUH@3805 ead328b1-e903-0410-a19d-eacee4b031f6

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -273,7 +273,7 @@ PACKAGE_BUGREPORT=''
 
 ac_subdirs_all="$ac_subdirs_all osprey/cygnus"
 ac_subdirs_all="$ac_subdirs_all osprey-gcc-4.2.0"
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os MACHINE_TYPE BUILD_ABI BUILD_ARCH BUILD_HOST BUILD_TARGET BUILD_VENDOR BUILD_OPTIMIZE BUILD_LIB_OPTIMIZE BUILD_COMPILER BUILD_BOTH LIB_MACHINE_TYPE LIB_BUILD_TARGET LIB_BUILD_ABI LIB_BUILD_ARCH LIB_BUILD_HOST LIB2_MACHINE_TYPE LIB2_BUILD_TARGET LIB2_BUILD_ABI LIB2_BUILD_ARCH LIB2_BUILD_HOST BUILD_MULTILIB COMPILER_TARG_DIR TARG_INFO_NAME BUILD_GNU3 BUILD_FORTRAN BUILD_SKIP_IPA BUILD_TYPE GCC_CONFIGURE_TARG GCC_DIR BUILD_TAU_INSTR BUILD_GNU4 ENABLE_COARRAYS GASNET_HOME ARMCI_HOME GASNET_CONDUIT ARMCI_CONDUIT LIBLIST subdirs LIBOBJS LTLIBOBJS uh_config_arguments'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os MACHINE_TYPE BUILD_ABI BUILD_ARCH BUILD_HOST BUILD_TARGET BUILD_VENDOR BUILD_OPTIMIZE BUILD_LIB_OPTIMIZE BUILD_COMPILER BUILD_BOTH LIB_MACHINE_TYPE LIB_BUILD_TARGET LIB_BUILD_ABI LIB_BUILD_ARCH LIB_BUILD_HOST LIB2_MACHINE_TYPE LIB2_BUILD_TARGET LIB2_BUILD_ABI LIB2_BUILD_ARCH LIB2_BUILD_HOST BUILD_MULTILIB COMPILER_TARG_DIR TARG_INFO_NAME BUILD_GNU3 BUILD_FORTRAN BUILD_SKIP_IPA BUILD_TYPE GCC_CONFIGURE_TARG GCC_DIR BUILD_TAU_INSTR BUILD_GNU4 ENABLE_COARRAYS GASNET_HOME ARMCI_HOME GASNET_CONDUITS DEFAULT_COMM BASH_PATH LIBLIST subdirs LIBOBJS LTLIBOBJS uh_config_arguments'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -804,10 +804,10 @@ Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
   --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
   --with-build-compiler=GNU|OSP	Use GNU or OSP compilers in build
-  --with-gasnet-root=gasnet path    Enables gasnet runtime for CAF
-  --with-gasnet-conduit   Use gasnet on specific conduit like IB,SMP,etc. Default is MPI
-  --with-armci-root=armci path    Enables armci runtime for CAF
-  --with-armci-conduit   Use armci on specific conduit like IB,MPI,etc. Default is MPI
+  --with-gasnet-root=<gasnet path>   Builds GASNet-based libcaf runtime
+  --with-armci-root=<armci path>     Builds ARMCI-based libcaf runtime
+  --with-default-comm=gasnet|armci   Default communication layer to use if GASNet and
+                                     ARMCI are supported.  Will be GASNet if unspecified.
   --with-build-optimize=DEFAULT|DEBUG	Use DEFAULT or DEBUG flags in compiler build
   --with-build-lib-optimize=DEFAULT|DEBUG Use DEFAULT or DEBUG flags in library build.
     Note that --with-build-lib-optimize=DEBUG is currently not well tested.
@@ -1407,16 +1407,8 @@ fi;
 if test "${with_gasnet_root+set}" = set; then
   withval="$with_gasnet_root"
   GASNET_HOME="$with_gasnet_root"
-fi;
-
-# enable GASNet Conduit
-
-# Check whether --with-gasnet-conduit or --without-gasnet-conduit was given.
-if test "${with_gasnet_conduit+set}" = set; then
-  withval="$with_gasnet_conduit"
-  GASNET_CONDUIT="$with_gasnet_conduit"
 else
-  GASNET_CONDUIT="MPI"
+  GASNET_HOME=""
 fi;
 
 # enable ARMCI for Coarrays
@@ -1425,17 +1417,28 @@ fi;
 if test "${with_armci_root+set}" = set; then
   withval="$with_armci_root"
   ARMCI_HOME="$with_armci_root"
-fi;
-
-# enable ARMCI Conduit
-
-# Check whether --with-armci-conduit or --without-armci-conduit was given.
-if test "${with_armci_conduit+set}" = set; then
-  withval="$with_armci_conduit"
-  ARMCI_CONDUIT="$with_armci_conduit"
 else
-  ARMCI_CONDUIT="MPI"
+  ARMCI_HOME=""
 fi;
+
+# default comm library
+
+# Check whether --with-default-comm or --without-default-comm was given.
+if test "${with_default_comm+set}" = set; then
+  withval="$with_default_comm"
+  DEFAULT_COMM="$with_default_comm"
+else
+  DEFAULT_COMM=""
+fi;
+
+# set perl path
+BASH_PATH=`which bash`
+
+if test -z "${BASH_PATH}"; then
+  { { echo "$as_me:$LINENO: error: \"Could not find bash on system\"" >&5
+echo "$as_me: error: \"Could not find bash on system\"" >&2;}
+   { (exit 1); exit 1; }; }
+fi
 
 if test "${ENABLE_COARRAYS}" = "YES" -a -z "${GASNET_HOME}" -a -z "${ARMCI_HOME}"; then
     { { echo "$as_me:$LINENO: error: \"Either --with-gasnet-root=<path> or --with-armci-root=<path> must be passed for coarrays\"" >&5
@@ -1449,17 +1452,26 @@ echo "$as_me: error: \"Environment variable MPI_INCLUDE must be set to valid MPI
    { (exit 1); exit 1; }; }
 fi
 
-if test "${ENABLE_COARRAYS}" = "YES" -a -n "${GASNET_HOME}" -a "${GASNET_CONDUIT}" = "MPI"  -a  ! -f "${MPI_INCLUDE}/mpi.h"; then
-    { { echo "$as_me:$LINENO: error: \"Environment variable MPI_INCLUDE must be set to valid MPI include directory when enabling coarrays with GASNET on MPI
-                  conduit\"" >&5
-echo "$as_me: error: \"Environment variable MPI_INCLUDE must be set to valid MPI include directory when enabling coarrays with GASNET on MPI
-                  conduit\"" >&2;}
-   { (exit 1); exit 1; }; }
+if test -n "${GASNET_HOME}"; then
+  GASNET_CONDUITS=`(cd ${GASNET_HOME}/include; echo *-conduit \
+                    | sed 's/-conduit//g')`
 fi
 
-if test "${ENABLE_COARRAYS}" = "YES" -a -n "${GASNET_HOME}" -a -n "${GASNET_CONDUIT}" -a "${GASNET_CONDUIT}" != "MPI" -a "${GASNET_CONDUIT}" != "SMP" -a "${GASNET_CONDUIT}" != "IB"; then
-    { { echo "$as_me:$LINENO: error: \"GASNET_CONDUIT should be MPI, IB, or SMP\"" >&5
-echo "$as_me: error: \"GASNET_CONDUIT should be MPI, IB, or SMP\"" >&2;}
+if test -z "${DEFAULT_COMM}" -a -n "${GASNET_HOME}"; then
+  DEFAULT_COMM=gasnet
+elif test -z "${DEFAULT_COMM}" -a -n "${ARMCI_HOME}" ; then
+  DEFAULT_COMM=armci
+elif test -n "${DEFAULT_COMM}" -a "${DEFAULT_COMM}" != "gasnet"  -a "${DEFAULT_COMM}" != "armci" ; then
+    { { echo "$as_me:$LINENO: error: \"--with-default-comm accepts gasnet or armci\"" >&5
+echo "$as_me: error: \"--with-default-comm accepts gasnet or armci\"" >&2;}
+   { (exit 1); exit 1; }; }
+elif test "${DEFAULT_COMM}" = "gasnet" -a -z "${GASNET_HOME}" ; then
+    { { echo "$as_me:$LINENO: error: \"default comm (gasnet) requires --with-gasnet-root to be specified\"" >&5
+echo "$as_me: error: \"default comm (gasnet) requires --with-gasnet-root to be specified\"" >&2;}
+   { (exit 1); exit 1; }; }
+elif test "${DEFAULT_COMM}" = "armci" -a -z "${ARMCI_HOME}" ; then
+    { { echo "$as_me:$LINENO: error: \"default comm (armci) requires --with-armci-root to be specified\"" >&5
+echo "$as_me: error: \"default comm (armci) requires --with-armci-root to be specified\"" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
@@ -1837,12 +1849,16 @@ export GCC_CONFIGURE_CFLAGS
 
 
 
+
 # List of configurable files to create in object directory.
                                                                                                                                                                                                                                                                     ac_config_files="$ac_config_files Makefile osprey/Makefile.gsetup osprey/targdir/include/Makefile osprey/targdir/driver/Makefile osprey/targdir/libiberty/Makefile osprey/targdir/targ_info/Makefile osprey/targdir/be/Makefile osprey/targdir/libelf/Makefile osprey/targdir/libelfutil/Makefile osprey/targdir/libdwarf/Makefile osprey/targdir/libunwindP/Makefile osprey/targdir/cg/Makefile osprey/targdir/wopt/Makefile osprey/targdir/ipl/Makefile osprey/targdir/lno/Makefile osprey/targdir/lw_inline/Makefile osprey/targdir/ipa/Makefile osprey/targdir/whirl2c/Makefile osprey/targdir/libcomutil/Makefile osprey/targdir/ir_tools/Makefile osprey/targdir/libcmplrs/Makefile osprey/targdir/libcif/Makefile osprey/targdir/arith/Makefile osprey/targdir/orc_ict/Makefile osprey/targdir/orc_intel/Makefile osprey/targdir/libkapi/Makefile"
 
 
+          ac_config_files="$ac_config_files osprey/scripts/omprun"
+
+
 if test "${BUILD_FORTRAN}" = "YES"; then
-                                                   ac_config_files="$ac_config_files osprey/targdir/whirl2f/Makefile osprey/targdir/crayf90/Makefile osprey/targdir/crayf90/fe90/Makefile osprey/targdir/crayf90/libf90sgi/Makefile osprey/targdir/crayf90/sgi/Makefile"
+                                                                       ac_config_files="$ac_config_files osprey/targdir/whirl2f/Makefile osprey/targdir/crayf90/Makefile osprey/targdir/crayf90/fe90/Makefile osprey/targdir/crayf90/libf90sgi/Makefile osprey/targdir/crayf90/sgi/Makefile osprey/scripts/uhcaf osprey/scripts/cafrun"
 
 fi
 
@@ -1894,8 +1910,17 @@ else
 fi
 
 if test "${BUILD_FORTRAN}" = "YES"; then
-                                                     ac_config_files="$ac_config_files osprey/targdir_lib/libfortran/Makefile osprey/targdir_lib/libu/Makefile osprey/targdir_lib/libcaf/Makefile osprey/targdir_lib/libcaf/armci/Makefile osprey/targdir_lib/libcaf/gasnet/Makefile"
+                                           ac_config_files="$ac_config_files osprey/targdir_lib/libfortran/Makefile osprey/targdir_lib/libu/Makefile osprey/targdir_lib/libcaf/Makefile osprey/targdir_lib/libcaf/armci/Makefile"
 
+   if test -n "${GASNET_CONDUITS}"; then
+     for conduit in $GASNET_CONDUITS; do
+                 ac_config_files="$ac_config_files osprey/targdir_lib/libcaf/gasnet-${conduit}/Makefile:osprey/targdir_lib/libcaf/gasnet/Makefile.in"
+
+     done
+   else
+                 ac_config_files="$ac_config_files osprey/targdir_lib/libcaf/gasnet/Makefile"
+
+   fi
 fi
 
 if test "${BUILD_TARGET}" = "X8664" || test "${BUILD_TARGET}" = "IA32"; then
@@ -1913,8 +1938,17 @@ if test $BUILD_MULTILIB = "YES"; then
                                                               ac_config_files="$ac_config_files osprey/targdir_lib2/Makefile:osprey/targdir_lib/Makefile.in osprey/targdir_lib2/include/Makefile:osprey/targdir_lib/include/Makefile.in osprey/targdir_lib2/libopenmp/Makefile:osprey/targdir_lib/libopenmp/Makefile.in osprey/targdir_lib2/libopenmp-pcl/Makefile:osprey/targdir_lib/libopenmp-pcl/Makefile.in osprey/targdir_lib2/libhugetlbfs/Makefile:osprey/targdir_lib/libhugetlbfs/Makefile.in osprey/targdir_lib2/libmv/Makefile:osprey/targdir_lib/libmv/Makefile.in"
 
   if test "${BUILD_FORTRAN}" = "YES"; then
-                                                      ac_config_files="$ac_config_files osprey/targdir_lib2/libfortran/Makefile:osprey/targdir_lib/libfortran/Makefile.in osprey/targdir_lib2/libu/Makefile:osprey/targdir_lib/libu/Makefile.in osprey/targdir_lib2/libcaf/Makefile:osprey/targdir_lib/libcaf/Makefile.in osprey/targdir_lib2/libcaf/armci/Makefile:osprey/targdir_lib/libcaf/armci/Makefile.in osprey/targdir_lib2/libcaf/gasnet/Makefile:osprey/targdir_lib/libcaf/gasnet/Makefile.in"
+                                            ac_config_files="$ac_config_files osprey/targdir_lib2/libfortran/Makefile:osprey/targdir_lib/libfortran/Makefile.in osprey/targdir_lib2/libu/Makefile:osprey/targdir_lib/libu/Makefile.in osprey/targdir_lib2/libcaf/Makefile:osprey/targdir_lib/libcaf/Makefile.in osprey/targdir_lib2/libcaf/armci/Makefile:osprey/targdir_lib/libcaf/armci/Makefile.in"
 
+    if test -n "${GASNET_CONDUITS}"; then
+      for conduit in $GASNET_CONDUITS; do
+                  ac_config_files="$ac_config_files osprey/targdir_lib2/libcaf/gasnet-${conduit}/Makefile:osprey/targdir_lib/libcaf/gasnet/Makefile.in"
+
+      done
+    else
+                  ac_config_files="$ac_config_files osprey/targdir_lib2/libcaf/gasnet/Makefile:osprey/targdir_lib/libcaf/gasnet/Makefile.in"
+
+    fi
   fi
   if test "${BUILD_TARGET}" = "X8664" || test "${BUILD_TARGET}" = "IA32"; then
                                   ac_config_files="$ac_config_files osprey/targdir_lib2/libopen64rt/Makefile:osprey/targdir_lib/libopen64rt/Makefile.in osprey/targdir_lib2/libinstr2/Makefile:osprey/targdir_lib/libinstr2/Makefile.in osprey/targdir_lib2/libacml_mv/Makefile:osprey/targdir_lib/libacml_mv/Makefile.in"
@@ -2515,11 +2549,14 @@ do
   "osprey/targdir/orc_ict/Makefile" ) CONFIG_FILES="$CONFIG_FILES osprey/targdir/orc_ict/Makefile" ;;
   "osprey/targdir/orc_intel/Makefile" ) CONFIG_FILES="$CONFIG_FILES osprey/targdir/orc_intel/Makefile" ;;
   "osprey/targdir/libkapi/Makefile" ) CONFIG_FILES="$CONFIG_FILES osprey/targdir/libkapi/Makefile" ;;
+  "osprey/scripts/omprun" ) CONFIG_FILES="$CONFIG_FILES osprey/scripts/omprun" ;;
   "osprey/targdir/whirl2f/Makefile" ) CONFIG_FILES="$CONFIG_FILES osprey/targdir/whirl2f/Makefile" ;;
   "osprey/targdir/crayf90/Makefile" ) CONFIG_FILES="$CONFIG_FILES osprey/targdir/crayf90/Makefile" ;;
   "osprey/targdir/crayf90/fe90/Makefile" ) CONFIG_FILES="$CONFIG_FILES osprey/targdir/crayf90/fe90/Makefile" ;;
   "osprey/targdir/crayf90/libf90sgi/Makefile" ) CONFIG_FILES="$CONFIG_FILES osprey/targdir/crayf90/libf90sgi/Makefile" ;;
   "osprey/targdir/crayf90/sgi/Makefile" ) CONFIG_FILES="$CONFIG_FILES osprey/targdir/crayf90/sgi/Makefile" ;;
+  "osprey/scripts/uhcaf" ) CONFIG_FILES="$CONFIG_FILES osprey/scripts/uhcaf" ;;
+  "osprey/scripts/cafrun" ) CONFIG_FILES="$CONFIG_FILES osprey/scripts/cafrun" ;;
   "osprey/targdir/gccfe/Makefile" ) CONFIG_FILES="$CONFIG_FILES osprey/targdir/gccfe/Makefile" ;;
   "osprey/targdir/gccfe/gnu/Makefile" ) CONFIG_FILES="$CONFIG_FILES osprey/targdir/gccfe/gnu/Makefile" ;;
   "osprey/targdir/g++fe/Makefile" ) CONFIG_FILES="$CONFIG_FILES osprey/targdir/g++fe/Makefile" ;;
@@ -2538,6 +2575,7 @@ do
   "osprey/targdir_lib/libu/Makefile" ) CONFIG_FILES="$CONFIG_FILES osprey/targdir_lib/libu/Makefile" ;;
   "osprey/targdir_lib/libcaf/Makefile" ) CONFIG_FILES="$CONFIG_FILES osprey/targdir_lib/libcaf/Makefile" ;;
   "osprey/targdir_lib/libcaf/armci/Makefile" ) CONFIG_FILES="$CONFIG_FILES osprey/targdir_lib/libcaf/armci/Makefile" ;;
+  "osprey/targdir_lib/libcaf/gasnet-${conduit}/Makefile" ) CONFIG_FILES="$CONFIG_FILES osprey/targdir_lib/libcaf/gasnet-${conduit}/Makefile:osprey/targdir_lib/libcaf/gasnet/Makefile.in" ;;
   "osprey/targdir_lib/libcaf/gasnet/Makefile" ) CONFIG_FILES="$CONFIG_FILES osprey/targdir_lib/libcaf/gasnet/Makefile" ;;
   "osprey/targdir_lib/libopen64rt/Makefile" ) CONFIG_FILES="$CONFIG_FILES osprey/targdir_lib/libopen64rt/Makefile" ;;
   "osprey/targdir_lib/libinstr2/Makefile" ) CONFIG_FILES="$CONFIG_FILES osprey/targdir_lib/libinstr2/Makefile" ;;
@@ -2553,6 +2591,7 @@ do
   "osprey/targdir_lib2/libu/Makefile" ) CONFIG_FILES="$CONFIG_FILES osprey/targdir_lib2/libu/Makefile:osprey/targdir_lib/libu/Makefile.in" ;;
   "osprey/targdir_lib2/libcaf/Makefile" ) CONFIG_FILES="$CONFIG_FILES osprey/targdir_lib2/libcaf/Makefile:osprey/targdir_lib/libcaf/Makefile.in" ;;
   "osprey/targdir_lib2/libcaf/armci/Makefile" ) CONFIG_FILES="$CONFIG_FILES osprey/targdir_lib2/libcaf/armci/Makefile:osprey/targdir_lib/libcaf/armci/Makefile.in" ;;
+  "osprey/targdir_lib2/libcaf/gasnet-${conduit}/Makefile" ) CONFIG_FILES="$CONFIG_FILES osprey/targdir_lib2/libcaf/gasnet-${conduit}/Makefile:osprey/targdir_lib/libcaf/gasnet/Makefile.in" ;;
   "osprey/targdir_lib2/libcaf/gasnet/Makefile" ) CONFIG_FILES="$CONFIG_FILES osprey/targdir_lib2/libcaf/gasnet/Makefile:osprey/targdir_lib/libcaf/gasnet/Makefile.in" ;;
   "osprey/targdir_lib2/libopen64rt/Makefile" ) CONFIG_FILES="$CONFIG_FILES osprey/targdir_lib2/libopen64rt/Makefile:osprey/targdir_lib/libopen64rt/Makefile.in" ;;
   "osprey/targdir_lib2/libinstr2/Makefile" ) CONFIG_FILES="$CONFIG_FILES osprey/targdir_lib2/libinstr2/Makefile:osprey/targdir_lib/libinstr2/Makefile.in" ;;
@@ -2686,8 +2725,9 @@ s,@BUILD_GNU4@,$BUILD_GNU4,;t t
 s,@ENABLE_COARRAYS@,$ENABLE_COARRAYS,;t t
 s,@GASNET_HOME@,$GASNET_HOME,;t t
 s,@ARMCI_HOME@,$ARMCI_HOME,;t t
-s,@GASNET_CONDUIT@,$GASNET_CONDUIT,;t t
-s,@ARMCI_CONDUIT@,$ARMCI_CONDUIT,;t t
+s,@GASNET_CONDUITS@,$GASNET_CONDUITS,;t t
+s,@DEFAULT_COMM@,$DEFAULT_COMM,;t t
+s,@BASH_PATH@,$BASH_PATH,;t t
 s,@LIBLIST@,$LIBLIST,;t t
 s,@subdirs@,$subdirs,;t t
 s,@LIBOBJS@,$LIBOBJS,;t t
