[CAF] support most recent version of ARMCI
Before, we used the (obsolete) ARMCI 1.4. This change will build the
compiler/runtime to work with the more recent ARMCI versions. This can be
downloaded along with the GA toolkit.

The steps to build the runtime with ARMCI are:

(1) Build and install latest version of ARMCI

(2) Either have MPI_INCLUDE set, or have mpicc in your path.

(2) When configuring the compiler/runtime, need to specify the ARMCI *source*
    directory (--with-armci-src-root=) rather than the ARMCi installation
    directory. The --with-armci-root= configure option is no longer available.

Thie commit also fixes a runtime bug for accessing remote addresses. The
pointer addresses returned by ARMCI_Malloc appear to be with respect to the
local address space for nodes that belong to the same SMP domain. This
adjustment is now made in order to support remote pointer dereferencing.

Other changes

* Fix the translation of an address read from a remote process, where the
process resides on a different SMP node and is not the designated "master"
process. The address translation requires that it be with respect to the local
address space if it falls within the symmetric heap, or that it be with
respect to its master's address space if it falls outside the symmetric heap.

* The configure script will print a summary of the OpenUH configuration settings
selected by the user. CAF-specific configuration settings are displayed if
coarrays are enabled.

Updating patch level to 3.0.16

Contributor: Deepak

git-svn-id: https://svn.open64.net/svnroot/open64/branches/OpenUH@4018 ead328b1-e903-0410-a19d-eacee4b031f6

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -273,7 +273,7 @@ PACKAGE_BUGREPORT=''
 
 ac_subdirs_all="$ac_subdirs_all osprey/cygnus"
 ac_subdirs_all="$ac_subdirs_all osprey-gcc-4.2.0"
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os MACHINE_TYPE BUILD_ABI BUILD_ARCH BUILD_HOST BUILD_TARGET BUILD_VENDOR BUILD_OPTIMIZE BUILD_LIB_OPTIMIZE BUILD_COMPILER BUILD_BOTH LIB_MACHINE_TYPE LIB_BUILD_TARGET LIB_BUILD_ABI LIB_BUILD_ARCH LIB_BUILD_HOST LIB2_MACHINE_TYPE LIB2_BUILD_TARGET LIB2_BUILD_ABI LIB2_BUILD_ARCH LIB2_BUILD_HOST BUILD_MULTILIB COMPILER_TARG_DIR TARG_INFO_NAME BUILD_GNU3 BUILD_FORTRAN BUILD_SKIP_IPA BUILD_TYPE DRAGON_SUPPORT GCC_CONFIGURE_TARG GCC_DIR BUILD_TAU_INSTR BUILD_GNU4 ENABLE_COARRAYS BUILD_CAF_RUNTIME GASNET_HOME ARMCI_HOME GASNET_CONDUITS DEFAULT_COMM BASH_PATH MPI_INCLUDE CAFRT_ENABLE_TRACES DEFAULT_CAF_HEAP_SIZE OPENUH_VERSION LIBLIST subdirs LIBOBJS LTLIBOBJS uh_config_arguments'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os MACHINE_TYPE BUILD_ABI BUILD_ARCH BUILD_HOST BUILD_TARGET BUILD_VENDOR BUILD_OPTIMIZE BUILD_LIB_OPTIMIZE BUILD_COMPILER BUILD_BOTH LIB_MACHINE_TYPE LIB_BUILD_TARGET LIB_BUILD_ABI LIB_BUILD_ARCH LIB_BUILD_HOST LIB2_MACHINE_TYPE LIB2_BUILD_TARGET LIB2_BUILD_ABI LIB2_BUILD_ARCH LIB2_BUILD_HOST BUILD_MULTILIB COMPILER_TARG_DIR TARG_INFO_NAME BUILD_GNU3 BUILD_FORTRAN BUILD_SKIP_IPA BUILD_TYPE DRAGON_SUPPORT GCC_CONFIGURE_TARG GCC_DIR BUILD_TAU_INSTR BUILD_GNU4 ENABLE_COARRAYS BUILD_CAF_RUNTIME GASNET_HOME ARMCI_HOME ARMCI_INCLUDE_DIR ARMCI_LIBS GASNET_CONDUITS DEFAULT_COMM BASH_PATH MPI_INCLUDE CAFRT_ENABLE_TRACES DEFAULT_CAF_HEAP_SIZE OPENUH_VERSION LIBLIST subdirs LIBOBJS LTLIBOBJS uh_config_arguments'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -809,7 +809,7 @@ Optional Packages:
   --with-build-compiler=GNU|OSP	Use GNU or OSP compilers in build
   --with-gasnet-root=<gasnet path>
                           Builds GASNet-based libcaf runtime
-  --with-armci-root=<armci path>
+  --with-armci-src-root=<armci path>
                           Builds ARMCI-based libcaf runtime
   --with-default-comm=gasnet|armci
                           Default communication layer to use if GASNet and
@@ -1422,14 +1422,20 @@ fi;
 # Check whether --enable-cafrt-traces or --disable-cafrt-traces was given.
 if test "${enable_cafrt_traces+set}" = set; then
   enableval="$enable_cafrt_traces"
-  CAFRT_ENABLE_TRACES="NOTRACE"
+  CAFRT_ENABLE_TRACES="NO"
 else
-  CAFRT_ENABLE_TRACES="TRACE"
+  CAFRT_ENABLE_TRACES="YES"
 fi;
 
 if test "x$enable_caf_runtime" != "xno"; then
 
   BUILD_CAF_RUNTIME="YES"
+
+fi
+
+if test "x$enable_caf_runtime" = "xno"; then
+
+  BUILD_CAF_RUNTIME="NO"
 
 fi
 
@@ -1450,12 +1456,12 @@ fi;
 
 # enable ARMCI for Coarrays
 
-# Check whether --with-armci-root or --without-armci-root was given.
-if test "${with_armci_root+set}" = set; then
-  withval="$with_armci_root"
-  ARMCI_HOME="$with_armci_root"
+# Check whether --with-armci-src-root or --without-armci-src-root was given.
+if test "${with_armci_src_root+set}" = set; then
+  withval="$with_armci_src_root"
+  ARMCI_SRC_HOME="$with_armci_src_root"
 else
-  ARMCI_HOME=""
+  ARMCI_SRC_HOME=""
 fi;
 
 
@@ -1497,10 +1503,10 @@ echo "$as_me: error: --enable-coarrays option is expected with --with-gasnet-roo
    " >&2;}
    { (exit 1); exit 1; }; }
 fi
-if test "${ENABLE_COARRAYS}" = "NO" -a -n "${ARMCI_HOME}"; then
-  { { echo "$as_me:$LINENO: error: --enable-coarrays option is expected with --with-armci-root
+if test "${ENABLE_COARRAYS}" = "NO" -a -n "${ARMCI_SRC_HOME}"; then
+  { { echo "$as_me:$LINENO: error: --enable-coarrays option is expected with --with-armci-src-root
    " >&5
-echo "$as_me: error: --enable-coarrays option is expected with --with-armci-root
+echo "$as_me: error: --enable-coarrays option is expected with --with-armci-src-root
    " >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -1526,24 +1532,46 @@ echo "$as_me: error: --enable-coarrays option is expected when using --with-caf-
    { (exit 1); exit 1; }; }
 fi
 
-if test "${BUILD_CAF_RUNTIME}" = "YES" -a -z "${GASNET_HOME}" -a -z "${ARMCI_HOME}"; then
-    { { echo "$as_me:$LINENO: error: Either --with-gasnet-root=<path> or --with-armci-root=<path> must be passed for coarrays" >&5
-echo "$as_me: error: Either --with-gasnet-root=<path> or --with-armci-root=<path> must be passed for coarrays" >&2;}
+if test "${BUILD_CAF_RUNTIME}" = "YES" -a -z "${GASNET_HOME}" -a -z "${ARMCI_SRC_HOME}"; then
+    { { echo "$as_me:$LINENO: error: Either --with-gasnet-root=<path> or --with-armci-src-root=<path> must be passed for coarrays" >&5
+echo "$as_me: error: Either --with-gasnet-root=<path> or --with-armci-src-root=<path> must be passed for coarrays" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
-if test "${BUILD_CAF_RUNTIME}" = "YES" -a -n "${ARMCI_HOME}"; then
-    if test ! -f "${MPI_INCLUDE}/mpi.h" -a -n "`which mpicc 2>/dev/null`"; then
-        d=`which mpicc 2>/dev/null`
-        MPI_INCLUDE=`dirname $d`/../include
-    else
-        { { echo "$as_me:$LINENO: error: Environment variable MPI_INCLUDE must be set to valid MPI include directory when enabling coarrays with ARMCI" >&5
+if test "${BUILD_CAF_RUNTIME}" = "YES" -a -n "${ARMCI_SRC_HOME}"; then
+    if test ! -f "${MPI_INCLUDE}/mpi.h"; then
+        if test -n "`which mpicc 2>/dev/null`"; then
+            d=`which mpicc 2>/dev/null`
+            MPI_INCLUDE=`dirname $d`/../include
+        else
+            { { echo "$as_me:$LINENO: error: Environment variable MPI_INCLUDE must be set to valid MPI include directory when enabling coarrays with ARMCI" >&5
 echo "$as_me: error: Environment variable MPI_INCLUDE must be set to valid MPI include directory when enabling coarrays with ARMCI" >&2;}
+   { (exit 1); exit 1; }; }
+        fi
+    fi
+    if test ! -d "${ARMCI_SRC_HOME}"; then
+        { { echo "$as_me:$LINENO: error: Specified --with-armci-src-root=<path> doesn't look right. Check path." >&5
+echo "$as_me: error: Specified --with-armci-src-root=<path> doesn't look right. Check path." >&2;}
+   { (exit 1); exit 1; }; }
+    fi
+    armci_flag_info=`(cd $ARMCI_SRC_HOME; make flags 2> /dev/null)`
+    ARMCI_INCLUDE_DIR=`echo "${armci_flag_info}" | grep "ARMCI headers" | sed 's/^.* //' 2> /dev/null`
+    ARMCI_HOME=`dirname ${ARMCI_INCLUDE_DIR}`
+    ARMCI_LIBS=`echo "${armci_flag_info}" | grep "LIBS=" | sed 's/ LIBS=//'`
+    ARMCI_LIBS=`eval echo ${ARMCI_LIBS}`
+    if test -z "${ARMCI_INCLUDE_DIR}"; then
+        { { echo "$as_me:$LINENO: error: Couldn't find configured ARMCI source directory. Check specified --with-armci-src-root=<path>." >&5
+echo "$as_me: error: Couldn't find configured ARMCI source directory. Check specified --with-armci-src-root=<path>." >&2;}
    { (exit 1); exit 1; }; }
     fi
 fi
 
 if test -n "${GASNET_HOME}"; then
+  if test ! -d "${GASNET_HOME}"; then
+      { { echo "$as_me:$LINENO: error: Specified --with-gasnet-root=<path> doesn't look right. Check path." >&5
+echo "$as_me: error: Specified --with-gasnet-root=<path> doesn't look right. Check path." >&2;}
+   { (exit 1); exit 1; }; }
+  fi
   GASNET_CONDUITS=`(cd ${GASNET_HOME}/include; echo *-conduit \
                     | sed 's/-conduit//g')`
   if test  "${GASNET_CONDUITS}" = "*"; then
@@ -1555,7 +1583,7 @@ fi
 
 if test -z "${DEFAULT_COMM}" -a -n "${GASNET_HOME}"; then
   DEFAULT_COMM=gasnet
-elif test -z "${DEFAULT_COMM}" -a -n "${ARMCI_HOME}" ; then
+elif test -z "${DEFAULT_COMM}" -a -n "${ARMCI_SRC_HOME}" ; then
   DEFAULT_COMM=armci
 elif test -n "${DEFAULT_COMM}" -a "${DEFAULT_COMM}" != "gasnet"  -a "${DEFAULT_COMM}" != "armci" ; then
     { { echo "$as_me:$LINENO: error: --with-default-comm accepts gasnet or armci" >&5
@@ -1565,9 +1593,9 @@ elif test "${DEFAULT_COMM}" = "gasnet" -a -z "${GASNET_HOME}" ; then
     { { echo "$as_me:$LINENO: error: default comm (gasnet) requires --with-gasnet-root to be specified" >&5
 echo "$as_me: error: default comm (gasnet) requires --with-gasnet-root to be specified" >&2;}
    { (exit 1); exit 1; }; }
-elif test "${DEFAULT_COMM}" = "armci" -a -z "${ARMCI_HOME}" ; then
-    { { echo "$as_me:$LINENO: error: default comm (armci) requires --with-armci-root to be specified" >&5
-echo "$as_me: error: default comm (armci) requires --with-armci-root to be specified" >&2;}
+elif test "${DEFAULT_COMM}" = "armci" -a -z "${ARMCI_SRC_HOME}" ; then
+    { { echo "$as_me:$LINENO: error: default comm (armci) requires --with-armci-src-root to be specified" >&5
+echo "$as_me: error: default comm (armci) requires --with-armci-src-root to be specified" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
@@ -1601,6 +1629,12 @@ fi;
 if test "x$enable_dragon_support" = "xyes"; then
 
   DRAGON_SUPPORT=YES
+
+fi
+
+if test "x$enable_dragon_support" != "xyes"; then
+
+  DRAGON_SUPPORT=NO
 
 fi
 
@@ -1940,6 +1974,8 @@ export GCC_CONFIGURE_TARG
 export GCC_CONFIGURE_CFLAGS
 
 # Variables to replace in the configurable files.
+
+
 
 
 
@@ -2871,6 +2907,8 @@ s,@ENABLE_COARRAYS@,$ENABLE_COARRAYS,;t t
 s,@BUILD_CAF_RUNTIME@,$BUILD_CAF_RUNTIME,;t t
 s,@GASNET_HOME@,$GASNET_HOME,;t t
 s,@ARMCI_HOME@,$ARMCI_HOME,;t t
+s,@ARMCI_INCLUDE_DIR@,$ARMCI_INCLUDE_DIR,;t t
+s,@ARMCI_LIBS@,$ARMCI_LIBS,;t t
 s,@GASNET_CONDUITS@,$GASNET_CONDUITS,;t t
 s,@DEFAULT_COMM@,$DEFAULT_COMM,;t t
 s,@BASH_PATH@,$BASH_PATH,;t t
@@ -3352,4 +3390,80 @@ cat > configargs.h <<EOF
 static const char configuration_arguments[] = "$uh_config_arguments_str";
 EOF
 
+#"####################
 
+# -----------------------
+# Final Configure Report
+# -----------------------
+{ echo "$as_me:$LINENO: " >&5
+echo "$as_me: " >&6;}
+{ echo "$as_me:$LINENO: ********************************************************************" >&5
+echo "$as_me: ********************************************************************" >&6;}
+{ echo "$as_me:$LINENO:                        OPENUH CONFIGURATION" >&5
+echo "$as_me:                        OPENUH CONFIGURATION" >&6;}
+{ echo "$as_me:$LINENO: ********************************************************************" >&5
+echo "$as_me: ********************************************************************" >&6;}
+{ echo "$as_me:$LINENO: " >&5
+echo "$as_me: " >&6;}
+{ echo "$as_me:$LINENO:    OPENUH_VERSION                 = $OPENUH_VERSION" >&5
+echo "$as_me:    OPENUH_VERSION                 = $OPENUH_VERSION" >&6;}
+{ echo "$as_me:$LINENO:    INSTALLATION PATH              = $prefix" >&5
+echo "$as_me:    INSTALLATION PATH              = $prefix" >&6;}
+{ echo "$as_me:$LINENO:    HOST                           = $host" >&5
+echo "$as_me:    HOST                           = $host" >&6;}
+{ echo "$as_me:$LINENO:    TARGET                         = $target" >&5
+echo "$as_me:    TARGET                         = $target" >&6;}
+{ echo "$as_me:$LINENO:    BUILD_COMPILER                 = $BUILD_COMPILER" >&5
+echo "$as_me:    BUILD_COMPILER                 = $BUILD_COMPILER" >&6;}
+{ echo "$as_me:$LINENO:    BUILD_OPTIMIZE                 = $BUILD_OPTIMIZE" >&5
+echo "$as_me:    BUILD_OPTIMIZE                 = $BUILD_OPTIMIZE" >&6;}
+{ echo "$as_me:$LINENO:    BUILD_LIB_OPTIMIZE             = $BUILD_LIB_OPTIMIZE" >&5
+echo "$as_me:    BUILD_LIB_OPTIMIZE             = $BUILD_LIB_OPTIMIZE" >&6;}
+{ echo "$as_me:$LINENO:    BUILD_GNU4 (front-end)         = $BUILD_GNU4" >&5
+echo "$as_me:    BUILD_GNU4 (front-end)         = $BUILD_GNU4" >&6;}
+{ echo "$as_me:$LINENO:    BUILD_GNU3 (front-end)         = $BUILD_GNU3" >&5
+echo "$as_me:    BUILD_GNU3 (front-end)         = $BUILD_GNU3" >&6;}
+{ echo "$as_me:$LINENO:    BUILD_FORTRAN                  = $BUILD_FORTRAN" >&5
+echo "$as_me:    BUILD_FORTRAN                  = $BUILD_FORTRAN" >&6;}
+{ echo "$as_me:$LINENO:    DRAGON_SUPPORT                 = $DRAGON_SUPPORT" >&5
+echo "$as_me:    DRAGON_SUPPORT                 = $DRAGON_SUPPORT" >&6;}
+{ echo "$as_me:$LINENO:    ENABLE_COARRAYS                = $ENABLE_COARRAYS" >&5
+echo "$as_me:    ENABLE_COARRAYS                = $ENABLE_COARRAYS" >&6;}
+if test "${ENABLE_COARRAYS}" = "YES"; then
+
+{ echo "$as_me:$LINENO:    BUILD_CAF_RUNTIME              = $BUILD_CAF_RUNTIME" >&5
+echo "$as_me:    BUILD_CAF_RUNTIME              = $BUILD_CAF_RUNTIME" >&6;}
+
+fi
+
+if test "${BUILD_CAF_RUNTIME}" = "YES"; then
+
+{ echo "$as_me:$LINENO:    CAFRT_ENABLE_TRACES            = $CAFRT_ENABLE_TRACES" >&5
+echo "$as_me:    CAFRT_ENABLE_TRACES            = $CAFRT_ENABLE_TRACES" >&6;}
+{ echo "$as_me:$LINENO:    DEFAULT_CAF_HEAP_SIZE          = $DEFAULT_CAF_HEAP_SIZE" >&5
+echo "$as_me:    DEFAULT_CAF_HEAP_SIZE          = $DEFAULT_CAF_HEAP_SIZE" >&6;}
+{ echo "$as_me:$LINENO:    DEFAULT_COMM                   = $DEFAULT_COMM" >&5
+echo "$as_me:    DEFAULT_COMM                   = $DEFAULT_COMM" >&6;}
+{ echo "$as_me:$LINENO:    GASNET_HOME                    = $GASNET_HOME" >&5
+echo "$as_me:    GASNET_HOME                    = $GASNET_HOME" >&6;}
+{ echo "$as_me:$LINENO:    GASNET_CONDUITS                = $GASNET_CONDUITS" >&5
+echo "$as_me:    GASNET_CONDUITS                = $GASNET_CONDUITS" >&6;}
+{ echo "$as_me:$LINENO:    ARMCI_HOME                     = $ARMCI_HOME" >&5
+echo "$as_me:    ARMCI_HOME                     = $ARMCI_HOME" >&6;}
+{ echo "$as_me:$LINENO:    ARMCI_INCLUDE_DIR              = $ARMCI_INCLUDE_DIR" >&5
+echo "$as_me:    ARMCI_INCLUDE_DIR              = $ARMCI_INCLUDE_DIR" >&6;}
+{ echo "$as_me:$LINENO:    ARMCI_LIBS                     = $ARMCI_LIBS" >&5
+echo "$as_me:    ARMCI_LIBS                     = $ARMCI_LIBS" >&6;}
+{ echo "$as_me:$LINENO:    MPI_INCLUDE                    = $MPI_INCLUDE" >&5
+echo "$as_me:    MPI_INCLUDE                    = $MPI_INCLUDE" >&6;}
+
+fi
+
+{ echo "$as_me:$LINENO:    BUILD_TAU_INSTR (experimental) = $BUILD_TAU_INSTR" >&5
+echo "$as_me:    BUILD_TAU_INSTR (experimental) = $BUILD_TAU_INSTR" >&6;}
+{ echo "$as_me:$LINENO: " >&5
+echo "$as_me: " >&6;}
+{ echo "$as_me:$LINENO: ********************************************************************" >&5
+echo "$as_me: ********************************************************************" >&6;}
+{ echo "$as_me:$LINENO: " >&5
+echo "$as_me: " >&6;}
