[CAF] support non-allocatable module coarrays and other checks/fixes
This commit adds support for non-allocatable ("save") coarrays declared in
modules. Also, it adds some checks in the configure build script for the
compiler, fixes a back-end bug relating to detection of element size, and
makes a few other improvements.

Summary:

* Handle coarrays declared in modules. Coarrays that are declared in module
  have the COMMON storage class. This adds support for these coarrays (was
  only handling allocatable and local save coarrays before).

* Fix calculation of element size on coarray accesses. This fixes the logic
  used to determine the element size of coarray accesses, though it is not yet
  addressing accesses of coarray components (for user-defined coarray types).
  The element type is now returned in array_ref_on_RHS and array_ref_on_LHS
  based on the desc machine type of the enclosing ILOAD or ISTORE node.

  Also, for statements of the form A(...)[p] = B(...) or A(...) = B(...)[p], a
  direct transfer is no longer generated if the RHS contains a type
  conversion.

* By default, OpenUH/Open64 will add two underscores to the end of symbols
  containing an underscore in Fortran codes, which is consistent with the g77
  underscoring policy. However, since uhcaf is generally used for F90+ codes,
  this adds fno-second-underscore option to it which is consistent with
  underscoring policies used by the recent GNU, Intel, and PGI Fortran
  compilers.

* When running configure, it will now give an error if a CAF configure option is
  given but --enable-coarrays is not.

* The runtime makefiles were not correctly checking for whether the traces is
  to be enabled, which should now be fixed.

* Renaming trace option and checking if traces enabled in cafrun. To make it
  somewhat more consistent with the names used in mpirun for various
  MPI implementations, this renames --log-info option to --trace.  Also, the
  --log-file option is now --trace-file. Correspondingly, the environment
  variable UHCAF_LOG_INFO is now UHCAF_TRACE and UHCAF_LOG_FILE is now
  UHCAF_TRACE_FILE.  Further, the cafrun script will print a warning if a
  trace option is specified but the CAF runtime doesn't support tracing (built
  with --disable-cafrt-traces).

Also, updating patch leve to 3.0.10.

Contributor: Deepak

git-svn-id: https://svn.open64.net/svnroot/open64/branches/OpenUH@3951 ead328b1-e903-0410-a19d-eacee4b031f6

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1417,9 +1417,9 @@ fi;
 # Check whether --enable-cafrt-traces or --disable-cafrt-traces was given.
 if test "${enable_cafrt_traces+set}" = set; then
   enableval="$enable_cafrt_traces"
-  CAFRT_ENABLE_TRACES="NOTRACES"
+  CAFRT_ENABLE_TRACES="NOTRACE"
 else
-  CAFRT_ENABLE_TRACES="TRACES"
+  CAFRT_ENABLE_TRACES="TRACE"
 fi;
 
 if test "x$enable_caf_runtime" != "xno"; then
@@ -1468,21 +1468,51 @@ fi;
 BASH_PATH=`which bash`
 
 if test -z "${BASH_PATH}"; then
-  { { echo "$as_me:$LINENO: error: \"Could not find bash on system\"" >&5
-echo "$as_me: error: \"Could not find bash on system\"" >&2;}
+  { { echo "$as_me:$LINENO: error: Could not find bash on system" >&5
+echo "$as_me: error: Could not find bash on system" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
+# check CAF configuration options ...
+
+if test "${ENABLE_COARRAYS}" = "NO" -a -n "${GASNET_HOME}"; then
+  { { echo "$as_me:$LINENO: error: --enable-coarrays option is expected with --with-gasnet-root
+   " >&5
+echo "$as_me: error: --enable-coarrays option is expected with --with-gasnet-root
+   " >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test "${ENABLE_COARRAYS}" = "NO" -a -n "${ARMCI_HOME}"; then
+  { { echo "$as_me:$LINENO: error: --enable-coarrays option is expected with --with-armci-root
+   " >&5
+echo "$as_me: error: --enable-coarrays option is expected with --with-armci-root
+   " >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test "${ENABLE_COARRAYS}" = "NO" -a "x$enable_caf_runtime" = "xno"; then
+  { { echo "$as_me:$LINENO: error: --enable-coarrays option is expected with --disable-caf-runtime
+   " >&5
+echo "$as_me: error: --enable-coarrays option is expected with --disable-caf-runtime
+   " >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test "${ENABLE_COARRAYS}" = "NO" -a "x$enable_cafrt_traces" = "xno"; then
+  { { echo "$as_me:$LINENO: error: --enable-coarrays option is expected with --disable-cafrt-traces
+   " >&5
+echo "$as_me: error: --enable-coarrays option is expected with --disable-cafrt-traces
+   " >&2;}
+   { (exit 1); exit 1; }; }
+fi
 
 if test "${BUILD_CAF_RUNTIME}" = "YES" -a -z "${GASNET_HOME}" -a -z "${ARMCI_HOME}"; then
-    { { echo "$as_me:$LINENO: error: \"Either --with-gasnet-root=<path> or --with-armci-root=<path> must be passed for coarrays\"" >&5
-echo "$as_me: error: \"Either --with-gasnet-root=<path> or --with-armci-root=<path> must be passed for coarrays\"" >&2;}
+    { { echo "$as_me:$LINENO: error: Either --with-gasnet-root=<path> or --with-armci-root=<path> must be passed for coarrays" >&5
+echo "$as_me: error: Either --with-gasnet-root=<path> or --with-armci-root=<path> must be passed for coarrays" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
 if test "${BUILD_CAF_RUNTIME}" = "YES" -a -n "${ARMCI_HOME}"  -a  ! -f "${MPI_INCLUDE}/mpi.h"; then
-    { { echo "$as_me:$LINENO: error: \"Environment variable MPI_INCLUDE must be set to valid MPI include directory when enabling coarrays with ARMCI\"" >&5
-echo "$as_me: error: \"Environment variable MPI_INCLUDE must be set to valid MPI include directory when enabling coarrays with ARMCI\"" >&2;}
+    { { echo "$as_me:$LINENO: error: Environment variable MPI_INCLUDE must be set to valid MPI include directory when enabling coarrays with ARMCI" >&5
+echo "$as_me: error: Environment variable MPI_INCLUDE must be set to valid MPI include directory when enabling coarrays with ARMCI" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
@@ -1490,8 +1520,8 @@ if test -n "${GASNET_HOME}"; then
   GASNET_CONDUITS=`(cd ${GASNET_HOME}/include; echo *-conduit \
                     | sed 's/-conduit//g')`
   if test  "${GASNET_CONDUITS}" = "*"; then
-      { { echo "$as_me:$LINENO: error: \"Specified --with-gasnet-root=<path> doesn't look right. Check path.\"" >&5
-echo "$as_me: error: \"Specified --with-gasnet-root=<path> doesn't look right. Check path.\"" >&2;}
+      { { echo "$as_me:$LINENO: error: Specified --with-gasnet-root=<path> doesn't look right. Check path." >&5
+echo "$as_me: error: Specified --with-gasnet-root=<path> doesn't look right. Check path." >&2;}
    { (exit 1); exit 1; }; }
   fi
 fi
@@ -1501,16 +1531,16 @@ if test -z "${DEFAULT_COMM}" -a -n "${GASNET_HOME}"; then
 elif test -z "${DEFAULT_COMM}" -a -n "${ARMCI_HOME}" ; then
   DEFAULT_COMM=armci
 elif test -n "${DEFAULT_COMM}" -a "${DEFAULT_COMM}" != "gasnet"  -a "${DEFAULT_COMM}" != "armci" ; then
-    { { echo "$as_me:$LINENO: error: \"--with-default-comm accepts gasnet or armci\"" >&5
-echo "$as_me: error: \"--with-default-comm accepts gasnet or armci\"" >&2;}
+    { { echo "$as_me:$LINENO: error: --with-default-comm accepts gasnet or armci" >&5
+echo "$as_me: error: --with-default-comm accepts gasnet or armci" >&2;}
    { (exit 1); exit 1; }; }
 elif test "${DEFAULT_COMM}" = "gasnet" -a -z "${GASNET_HOME}" ; then
-    { { echo "$as_me:$LINENO: error: \"default comm (gasnet) requires --with-gasnet-root to be specified\"" >&5
-echo "$as_me: error: \"default comm (gasnet) requires --with-gasnet-root to be specified\"" >&2;}
+    { { echo "$as_me:$LINENO: error: default comm (gasnet) requires --with-gasnet-root to be specified" >&5
+echo "$as_me: error: default comm (gasnet) requires --with-gasnet-root to be specified" >&2;}
    { (exit 1); exit 1; }; }
 elif test "${DEFAULT_COMM}" = "armci" -a -z "${ARMCI_HOME}" ; then
-    { { echo "$as_me:$LINENO: error: \"default comm (armci) requires --with-armci-root to be specified\"" >&5
-echo "$as_me: error: \"default comm (armci) requires --with-armci-root to be specified\"" >&2;}
+    { { echo "$as_me:$LINENO: error: default comm (armci) requires --with-armci-root to be specified" >&5
+echo "$as_me: error: default comm (armci) requires --with-armci-root to be specified" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
