[UH_INSTR] adds alternate UH instrumentation phase
With this commit, the user can specify an alternate instrumentation,
implemented in wn_uhinstrument.cxx. It is almost exactly the instrumentation
phase implemented for integration with KOJAK and ther tools in a previously
funded project (COPPER). Before, use of this instrumentation required
configuring the compiler with --enable-tau-instrumentation. Now, it can simply
be invoked when compiling the source code with the -uhinstr flag.

Additionally, by setting the environment variable OPENUH_USE_LIBUHINSTR to
'yes', the compiler will link in its internal libuhinstr (formerly called
libepilog) along with TAU libraries that it uses. For this support, the
compiler should be configured with:
    --enable-libuhinstr --with-tau-makefile=<a tau makefile>.

The new UH instrumentation is still in a development phase, and in particular
FDO may not work with it. But it can be used to instrument codes using TAU,
and VampirTrace also provides an external implementation of the UH
instrumentation API which may be used.

Contributor: Deepak, Oscar

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -273,7 +273,7 @@ PACKAGE_BUGREPORT=''
 
 ac_subdirs_all="$ac_subdirs_all osprey/cygnus"
 ac_subdirs_all="$ac_subdirs_all osprey-gcc-4.2.0"
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os MACHINE_TYPE CROSS_TARGET BUILD_ABI BUILD_ARCH BUILD_HOST BUILD_TARGET BUILD_VENDOR BUILD_OPTIMIZE BUILD_FFE_OPTIMIZE BUILD_LIB_OPTIMIZE BUILD_COMPILER BUILD_BOTH LIB_MACHINE_TYPE LIB_BUILD_TARGET LIB_BUILD_ABI LIB_BUILD_ARCH LIB_BUILD_HOST LIB2_MACHINE_TYPE LIB2_BUILD_TARGET LIB2_BUILD_ABI LIB2_BUILD_ARCH LIB2_BUILD_HOST BUILD_MULTILIB COMPILER_TARG_DIR TARG_INFO_NAME BUILD_GNU3 BUILD_FORTRAN WHIRL_HAS_ID_FIELD BUILD_SKIP_IPA BUILD_TYPE DRAGON_SUPPORT GCC_CONFIGURE_TARG GCC_DIR BUILD_TAU_INSTR BUILD_GNU4 ENABLE_COARRAYS BUILD_CAF_RUNTIME GASNET_HOME ARMCI_HOME ARMCI_NETWORK_LIBS GASNET_CONDUITS DEFAULT_COMM BASH_PATH MPI_INCLUDE CAFRT_ENABLE_TRACES DEFAULT_CAF_HEAP_SIZE OPENUH_VERSION LIBLIST subdirs LIBOBJS LTLIBOBJS uh_config_arguments'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os MACHINE_TYPE CROSS_TARGET BUILD_ABI BUILD_ARCH BUILD_HOST BUILD_TARGET BUILD_VENDOR BUILD_OPTIMIZE BUILD_FFE_OPTIMIZE BUILD_LIB_OPTIMIZE BUILD_COMPILER BUILD_BOTH LIB_MACHINE_TYPE LIB_BUILD_TARGET LIB_BUILD_ABI LIB_BUILD_ARCH LIB_BUILD_HOST LIB2_MACHINE_TYPE LIB2_BUILD_TARGET LIB2_BUILD_ABI LIB2_BUILD_ARCH LIB2_BUILD_HOST BUILD_MULTILIB COMPILER_TARG_DIR TARG_INFO_NAME BUILD_GNU3 BUILD_FORTRAN WHIRL_HAS_ID_FIELD BUILD_SKIP_IPA BUILD_TYPE DRAGON_SUPPORT GCC_CONFIGURE_TARG GCC_DIR BUILD_GNU4 ENABLE_COARRAYS BUILD_CAF_RUNTIME GASNET_HOME ARMCI_HOME ARMCI_NETWORK_LIBS GASNET_CONDUITS DEFAULT_COMM BASH_PATH MPI_INCLUDE CAFRT_ENABLE_TRACES DEFAULT_CAF_HEAP_SIZE BUILD_LIBUHINSTR TAU_ROOT TAU_LIBS OPENUH_VERSION LIBLIST subdirs LIBOBJS LTLIBOBJS uh_config_arguments'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -800,8 +800,7 @@ Optional Features:
   --enable-whirl-id       Enable debugging ID in WHIRL node
   --disable-ipa           Disable IPA compilation support (EXPERIMENTAL)
   --disable-shared        Disable shared libraries (EXPERIMENTAL)
-  --enable-tau-instrumentation
-                          Enable TAU instrumentation (EXPERIMENTAL)
+  --enable-libuhinstr     Enable UH Instrumentation Library (EXPERIMENTAL)
   --disable-gnu4          Disable GNU4-based C/C++ frontend
 
 Optional Packages:
@@ -827,6 +826,9 @@ Optional Packages:
   --with-build-ffe-optimize=DEFAULT|DEBUG Use DEFAULT or DEBUG flags in FFE build
   --with-build-lib-optimize=DEFAULT|DEBUG Use DEFAULT or DEBUG flags in library build.
     Note that --with-build-lib-optimize=DEBUG is currently not well tested.
+  --with-tau-makefile=<path to TAU makefile>
+                          Path to a TAU Makefile (assumed to be in
+                          $TAU_ROOT/$ARCH/lib/
 
 _ACEOF
 fi
@@ -1508,6 +1510,7 @@ echo "$as_me: error: Could not find bash on system" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
+
 # check CAF configuration options ...
 
 if test "${ENABLE_COARRAYS}" = "NO" -a -n "${GASNET_HOME}"; then
@@ -1814,17 +1817,49 @@ if test "${BUILD_TYPE}" = "NONSHARED"; then
   BUILD_SKIP_IPA=YES
 fi
 
-# enable TAU instrumentation
-# Check whether --enable-tau-instrumentation or --disable-tau-instrumentation was given.
-if test "${enable_tau_instrumentation+set}" = set; then
-  enableval="$enable_tau_instrumentation"
+# build libuhinstr library
+# Check whether --enable-libuhinstr or --disable-libuhinstr was given.
+if test "${enable_libuhinstr+set}" = set; then
+  enableval="$enable_libuhinstr"
 
 fi;
 
-if test "x$enable_tau_instrumentation" = "xyes"; then
+if test "x$enable_libuhinstr" = "xyes"; then
 
-  BUILD_TAU_INSTR=YES
+  BUILD_LIBUHINSTR=YES
 
+fi
+
+
+
+# Check whether --with-tau-makefile or --without-tau-makefile was given.
+if test "${with_tau_makefile+set}" = set; then
+  withval="$with_tau_makefile"
+  TAU_MAKEFILE="$with_tau_makefile"
+else
+  TAU_MAKEFILE=""
+fi;
+
+if test "${BUILD_LIBUHINSTR}" = "YES" -a -z "${TAU_MAKEFILE}"; then
+  { { echo "$as_me:$LINENO: error: --with-tau-makefile= should be specified along with --enable-libuhinstr
+   " >&5
+echo "$as_me: error: --with-tau-makefile= should be specified along with --enable-libuhinstr
+   " >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+if test -n "${TAU_MAKEFILE}"; then
+  if test ! -f "${TAU_MAKEFILE}"; then
+      { { echo "$as_me:$LINENO: error: File does not exist: $TAU_MAKEFILE" >&5
+echo "$as_me: error: File does not exist: $TAU_MAKEFILE" >&2;}
+   { (exit 1); exit 1; }; }
+  fi
+  TAU_ROOT="`dirname $TAU_MAKEFILE`/../.."
+  tau_bin="`dirname $TAU_MAKEFILE`/../bin/"
+  TAU_LIBS=`TAU_MAKEFILE=${TAU_MAKEFILE} ${tau_bin}/tau_cc.sh -tau:showlibs`
+else
+  TAU_ROOT=""
+  TAU_LIBS=""
 fi
 
 
@@ -2099,6 +2134,8 @@ export GCC_CONFIGURE_CFLAGS
 
 
 
+
+
 # List of configurable files to create in object directory.
                                                                                                                                                                                                                                                                     ac_config_files="$ac_config_files Makefile osprey/Makefile.gsetup osprey/targdir/include/Makefile osprey/targdir/driver/Makefile osprey/targdir/libiberty/Makefile osprey/targdir/targ_info/Makefile osprey/targdir/be/Makefile osprey/targdir/libelf/Makefile osprey/targdir/libelfutil/Makefile osprey/targdir/libdwarf/Makefile osprey/targdir/libunwindP/Makefile osprey/targdir/cg/Makefile osprey/targdir/wopt/Makefile osprey/targdir/ipl/Makefile osprey/targdir/lno/Makefile osprey/targdir/lw_inline/Makefile osprey/targdir/ipa/Makefile osprey/targdir/whirl2c/Makefile osprey/targdir/libcomutil/Makefile osprey/targdir/ir_tools/Makefile osprey/targdir/libcmplrs/Makefile osprey/targdir/libcif/Makefile osprey/targdir/arith/Makefile osprey/targdir/orc_ict/Makefile osprey/targdir/orc_intel/Makefile osprey/targdir/libkapi/Makefile"
 
@@ -2188,6 +2225,12 @@ if test "${BUILD_TARGET}" = "IA64" ; then
             ac_config_files="$ac_config_files osprey/targdir_lib/init/Makefile:osprey/targdir_lib/init/Makefile.in"
 
 fi
+if test "${BUILD_LIBUHINSTR}" == "YES"; then
+  LIBLIST="$LIBLIST libuhinstr"
+            ac_config_files="$ac_config_files osprey/targdir_lib/libuhinstr/Makefile"
+
+fi
+
 
 if test $BUILD_MULTILIB = "YES"; then
                                                               ac_config_files="$ac_config_files osprey/targdir_lib2/Makefile:osprey/targdir_lib/Makefile.in osprey/targdir_lib2/include/Makefile:osprey/targdir_lib/include/Makefile.in osprey/targdir_lib2/libopenmp/Makefile:osprey/targdir_lib/libopenmp/Makefile.in osprey/targdir_lib2/libopenmp-pcl/Makefile:osprey/targdir_lib/libopenmp-pcl/Makefile.in osprey/targdir_lib2/libhugetlbfs/Makefile:osprey/targdir_lib/libhugetlbfs/Makefile.in osprey/targdir_lib2/libmv/Makefile:osprey/targdir_lib/libmv/Makefile.in"
@@ -2207,6 +2250,10 @@ if test $BUILD_MULTILIB = "YES"; then
   fi
   if test "${BUILD_TARGET}" = "X8664" || test "${BUILD_TARGET}" = "IA32"; then
                                   ac_config_files="$ac_config_files osprey/targdir_lib2/libopen64rt/Makefile:osprey/targdir_lib/libopen64rt/Makefile.in osprey/targdir_lib2/libinstr2/Makefile:osprey/targdir_lib/libinstr2/Makefile.in osprey/targdir_lib2/libacml_mv/Makefile:osprey/targdir_lib/libacml_mv/Makefile.in"
+
+  fi
+  if test "${BUILD_LIBUHINSTR}" == "YES"; then
+              ac_config_files="$ac_config_files osprey/targdir_lib2/libuhinstr/Makefile:osprey/targdir_lib/libuhinstr/Makefile.in"
 
   fi
 fi
@@ -2837,6 +2884,7 @@ do
   "osprey/targdir_lib/libinstr2/Makefile" ) CONFIG_FILES="$CONFIG_FILES osprey/targdir_lib/libinstr2/Makefile" ;;
   "osprey/targdir_lib/libacml_mv/Makefile" ) CONFIG_FILES="$CONFIG_FILES osprey/targdir_lib/libacml_mv/Makefile" ;;
   "osprey/targdir_lib/init/Makefile" ) CONFIG_FILES="$CONFIG_FILES osprey/targdir_lib/init/Makefile:osprey/targdir_lib/init/Makefile.in" ;;
+  "osprey/targdir_lib/libuhinstr/Makefile" ) CONFIG_FILES="$CONFIG_FILES osprey/targdir_lib/libuhinstr/Makefile" ;;
   "osprey/targdir_lib2/Makefile" ) CONFIG_FILES="$CONFIG_FILES osprey/targdir_lib2/Makefile:osprey/targdir_lib/Makefile.in" ;;
   "osprey/targdir_lib2/include/Makefile" ) CONFIG_FILES="$CONFIG_FILES osprey/targdir_lib2/include/Makefile:osprey/targdir_lib/include/Makefile.in" ;;
   "osprey/targdir_lib2/libopenmp/Makefile" ) CONFIG_FILES="$CONFIG_FILES osprey/targdir_lib2/libopenmp/Makefile:osprey/targdir_lib/libopenmp/Makefile.in" ;;
@@ -2853,6 +2901,7 @@ do
   "osprey/targdir_lib2/libopen64rt/Makefile" ) CONFIG_FILES="$CONFIG_FILES osprey/targdir_lib2/libopen64rt/Makefile:osprey/targdir_lib/libopen64rt/Makefile.in" ;;
   "osprey/targdir_lib2/libinstr2/Makefile" ) CONFIG_FILES="$CONFIG_FILES osprey/targdir_lib2/libinstr2/Makefile:osprey/targdir_lib/libinstr2/Makefile.in" ;;
   "osprey/targdir_lib2/libacml_mv/Makefile" ) CONFIG_FILES="$CONFIG_FILES osprey/targdir_lib2/libacml_mv/Makefile:osprey/targdir_lib/libacml_mv/Makefile.in" ;;
+  "osprey/targdir_lib2/libuhinstr/Makefile" ) CONFIG_FILES="$CONFIG_FILES osprey/targdir_lib2/libuhinstr/Makefile:osprey/targdir_lib/libuhinstr/Makefile.in" ;;
   *) { { echo "$as_me:$LINENO: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
@@ -2981,7 +3030,6 @@ s,@BUILD_TYPE@,$BUILD_TYPE,;t t
 s,@DRAGON_SUPPORT@,$DRAGON_SUPPORT,;t t
 s,@GCC_CONFIGURE_TARG@,$GCC_CONFIGURE_TARG,;t t
 s,@GCC_DIR@,$GCC_DIR,;t t
-s,@BUILD_TAU_INSTR@,$BUILD_TAU_INSTR,;t t
 s,@BUILD_GNU4@,$BUILD_GNU4,;t t
 s,@ENABLE_COARRAYS@,$ENABLE_COARRAYS,;t t
 s,@BUILD_CAF_RUNTIME@,$BUILD_CAF_RUNTIME,;t t
@@ -2994,6 +3042,9 @@ s,@BASH_PATH@,$BASH_PATH,;t t
 s,@MPI_INCLUDE@,$MPI_INCLUDE,;t t
 s,@CAFRT_ENABLE_TRACES@,$CAFRT_ENABLE_TRACES,;t t
 s,@DEFAULT_CAF_HEAP_SIZE@,$DEFAULT_CAF_HEAP_SIZE,;t t
+s,@BUILD_LIBUHINSTR@,$BUILD_LIBUHINSTR,;t t
+s,@TAU_ROOT@,$TAU_ROOT,;t t
+s,@TAU_LIBS@,$TAU_LIBS,;t t
 s,@OPENUH_VERSION@,$OPENUH_VERSION,;t t
 s,@LIBLIST@,$LIBLIST,;t t
 s,@subdirs@,$subdirs,;t t
@@ -3536,8 +3587,17 @@ echo "$as_me:    MPI_INCLUDE                    = $MPI_INCLUDE" >&6;}
 
 fi
 
-{ echo "$as_me:$LINENO:    BUILD_TAU_INSTR (experimental) = $BUILD_TAU_INSTR" >&5
-echo "$as_me:    BUILD_TAU_INSTR (experimental) = $BUILD_TAU_INSTR" >&6;}
+if test "${BUILD_LIBUHINSTR}" = "YES"; then
+
+{ echo "$as_me:$LINENO:    BUILD_LIBUHINSTR               = $BUILD_LIBUHINSTR" >&5
+echo "$as_me:    BUILD_LIBUHINSTR               = $BUILD_LIBUHINSTR" >&6;}
+{ echo "$as_me:$LINENO:    TAU_ROOT                       = $TAU_ROOT" >&5
+echo "$as_me:    TAU_ROOT                       = $TAU_ROOT" >&6;}
+{ echo "$as_me:$LINENO:    TAU_LIBS                       = $TAU_LIBS" >&5
+echo "$as_me:    TAU_LIBS                       = $TAU_LIBS" >&6;}
+
+fi
+
 { echo "$as_me:$LINENO: " >&5
 echo "$as_me: " >&6;}
 { echo "$as_me:$LINENO: ********************************************************************" >&5
