[CAF] fix reservation of symmetric heap + misc script improvements
This commit fixes reservation of the symmetric heap space, particularly when
attempting to reserve more than 2 GB of heap space.  There were a number fo
issues that needed to be fixed:

* In a recent change, when I read in the environment variable for
  UHCAF_IMAGE_HEAP_SIZE if it exceeded 4 GB (32-bit size) the code would read
  it as 0. Needed to replace a call to atoi with atoll.

* In the general case, I was setting GASNET_MAX_SEGSIZE to a value less than
  UHCAF_IMAGE_HEAP_SIZE when UHCAF_IMAGE_HEAP_SIZE > 2000000000.

* And even if GASNET_MAX_SEGSIZE  = UHCAF_IMAGE_HEAP_SIZE, its not enough
  because GASNet appears to reserve 2 MB of the segment for something.

Now, it reserves enough space so that GASNET_MAX_SEGSIZE will
always be a page-size multiple and at least 2 MB greater than what was
requested.  During runtime, instead of giving an error if the
UHCAF_IMAGE_HEAP_SIZE is still greater than the maximum segment size, it will
display a warning and use the lesser value.

The cafrun script has been improved. Options provided by the underlying
launcher (e.g. mpirun) can be specified after the "--" at the end of the
command line. These options will be joined with the existing options specified
in LAUNCHER_OPTS.

More:

* --help menu only displays the help options. To see the environment
    variables, use --help-env.
* adds a --version option.
* --show will print the executable name and the communication layer and
  network it will run on.
* -np is accepted for specifying number of images  (same as -n and
  --num-images=)

Further, improvements were made in uhcaf compile script and cafrun launch
script to automatically identify which MPI libraries need to be linked in and
also which launcher to use if unspecified by the user. Its tested with Open
MPI and MVAPICH. When compiling, instead of using the variable LIBMPI to
specify the libraries to link in, the variable MPI_LD_LIBS is used.

Our current implementation imposes a limit on number of images (1024*1024) and
heap size per image (64GB). This commit adds a checks for these values during
initialization.

MPI_INCLUDE needs to be set to build the runtime against the ARMCI libraries.
The configure script will now set the MPI include path if it finds mpicc in
the user's path.  When compiling a CAF program with ARMCI layer, MPI_LIB needs
to be set. The compile script will similarly set MPI_LIB if it finds mpicc in
the path.

Contributor: Deepak

git-svn-id: https://svn.open64.net/svnroot/open64/branches/OpenUH@3996 ead328b1-e903-0410-a19d-eacee4b031f6

diff --git a/osprey/scripts/cafrun.in b/osprey/scripts/cafrun.in
--- a/osprey/scripts/cafrun.in
+++ b/osprey/scripts/cafrun.in
@@ -37,6 +37,13 @@ fi
 
 default_heap_size=@DEFAULT_CAF_HEAP_SIZE@
 
+version_num=@OPENUH_VERSION@
+
+GASNET_HOME=@GASNET_HOME@
+ARMCI_HOME=@ARMCI_HOME@
+default_comm=@DEFAULT_COMM@
+
+
 ENVIRONMENT="-----------------------\n"
 
 this_usage_short()
@@ -55,43 +62,22 @@ _EOT_
 
 }
 
-this_usage()
+print_version_info()
+{
+  echo " cafrun: $version_num"
+  echo ""
+  echo " Script for running CAF programs compiled with OpenUH"
+  echo " Copyright (C) University of Houston"
+  echo ""
+}
+
+this_usage_env()
 {
   cat <<_EOT_
 
-Usage: $this  [OPTIONS]... PROGRAM... -- [LAUNCHER OPTIONS]...
-
-Where options are
-
-  --num-images=N      N is number of images to use
-  -n N                N is number of images to use
-
-  --trace=L           Sets trace levels for runtime.
-                      L=all or trace levels delimited by ':'.
-                        Available trace levels:
-                        FATAL:DEBUG:TIME:NOTICE:TIME_SUMMARY:INIT:MEMORY:
-                        CACHE:BARRIER:REDUCE:SYMBOLS:SERVICE
-
-  --trace-file=F      F is name of file to store trace
-
-  --image-heap=I      I is heap size per image for storing coarray data. It
-                      may be an integer which indicates size in bytes, or it
-                      may have the suffixes K, M, G which indicates size in
-                      kilobytes, megabytes, and gigabytes, respectively.
-
-  --help              Displays this menu
-
-  --help2             Displays more options for underlying launcher
-
-  --verbose           Verbose output
-
-  --show              Display launch settings and exit
-
 Environment Variables:
 
-   LAUNCHER           Underlying launcher to use for launching CAF images
-                      for the specified program.
-                         By default, set to: $LAUNCHER
+   LAUNCHER           Underlying launcher to use for the specified program
 
    LAUNCHER_OPTS      Additional options to pass to underlying launcher
 
@@ -127,6 +113,47 @@ Environment Variables:
                       getcache optimizer. By default it is 64KB.
 
 _EOT_
+}
+
+this_usage()
+{
+  cat <<_EOT_
+
+Usage: $this  [OPTIONS]... PROGRAM... -- [LAUNCHER OPTIONS]...
+
+Where OPTIONS are:
+
+  --num-images=N
+  -n,-np N            N is number of images to use
+
+  --trace=L           Sets trace levels for runtime.
+                      L=all or trace levels delimited by ':'.
+                        Available trace levels:
+                        FATAL:DEBUG:TIME:NOTICE:TIME_SUMMARY:INIT:MEMORY:
+                        CACHE:BARRIER:REDUCE:SYMBOLS:SERVICE
+
+  --trace-file=F      F is name of file to store trace
+
+  --image-heap=I      I is heap size per image for storing coarray data. It
+                      may be an integer which indicates size in bytes, or it
+                      may have the suffixes K, M, G which indicates size in
+                      kilobytes, megabytes, and gigabytes, respectively.
+
+  --verbose,-v        Verbose output
+
+  --show              Display launch settings and command, but does not run
+                      program
+
+  --help              Prints this menu and exits
+
+  --help2             Prints underlying LAUNCHER OPTIONS and exits
+
+  --help-env          Prints available environment variables for controlling
+                      runtime environment and exits
+
+  --version,-V        Print version of cafrun and exits
+
+_EOT_
 
 }
 
@@ -160,20 +187,37 @@ set_env()
 
 print_error()
 {
-  echo "Error: $1" >&2
+  echo -e "Error: $*" >&2
   exit 1
 }
 
 print_warning()
 {
-  echo "Warning: $1" >&2
+  echo -e "Warning: $*" >&2
 }
 
 
 # -------------------------------------------------------------------
 
+# default launcher for gasnet-built programs
+gasnet_launcher=`which mpirun 2> /dev/null`
+if [ -f $GASNET_HOME/bin/gasnetrun_mpi ]; then
+   eval `grep MPIRUN_CMD= $GASNET_HOME/bin/gasnetrun_mpi`
+   gasnet_launcher=${MPIRUN_CMD%% *}
+fi
+
+#default launcher for armci-built programs
+armci_launcher=`which mpirun 2> /dev/null`
+
+############################################################
+# set default launcher if its not already set
 if [ -z "$LAUNCHER" ]; then
-  LAUNCHER=mpirun
+  # find a suitable, default launcher
+  if [ "$default_comm" = "gasnet" ]; then
+    LAUNCHER=$gasnet_launcher
+  else
+    LAUNCHER=$armci_launcher
+  fi
 fi
 
 if [ $# -eq 0 ]; then
@@ -190,6 +234,7 @@ arg_num=0
 option_parse=yes
 display_help=no
 display_help2=no
+program_name_seen=no
 
 process_num_images=no
 for arg in "$@" ; do
@@ -209,70 +254,100 @@ for arg in "$@" ; do
       continue
   fi
 
-  case "$arg" in
-    -v|--verbose)
-      verbose=yes
-      ;;
-    --show)
-      verbose=yes
-      show=yes
-      ;;
-    --help)
-      this_usage
-      display_help=yes
-      ;;
-    --help2)
-      display_help2=yes
-      ;;
-    --num-images=*)
-      num_images=`echo UhCaf$arg | sed -e 's/UhCaf--num-images=//g'`
-      if ! [[ "$num_images" =~ ^[0-9]+$ ]]; then
-        print_error "num-images specified is not valid"
-      fi
-      ;;
-    -n)
-      # next arg should be number of images
-      process_num_images=yes
-      ;;
-    --trace=*)
-      levels=`echo UhCaf$arg | sed -e 's/UhCaf--trace=//g'`
-      levels=`echo $levels | tr '[:lower:]' '[:upper:]'`
-      set_env UHCAF_TRACE $levels
-      if [ "${traces_enabled}" = "no" ]; then
-        print_warning "Traces disabled in CAF runtime"
-      fi
-      ;;
-    --trace-file=*)
-      trace_file=`echo UhCaf$arg | sed -e 's/UhCaf--trace-file=//g'`
-      set_env UHCAF_TRACE_FILE $trace_file
-      if [ "${traces_enabled}" = "no" ]; then
-        print_warning "Traces disabled in CAF runtime"
-      fi
-      ;;
-    --image-heap=*)
-      image_heap=`echo UhCaf$arg | sed -e 's/UhCaf--image-heap=//g'`
+  if [ $program_name_seen = no ]; then
 
-      if [[ ! $image_heap =~ ^[0-9]+$ ]]; then
-        if [[  $image_heap =~ ^[0-9]+[kK]$ ]]; then
-          image_heap=$((${image_heap%?}*1024))
-        elif [[ $image_heap =~ ^[0-9]+[mM]$ ]]; then
-          image_heap=$((${image_heap%?}*1024*1024))
-        elif [[ $image_heap =~ ^[0-9]+[gG]$ ]]; then
-          image_heap=$((${image_heap%?}*1024*1024*1024))
-        else
-          print_error "Invalid per-image heap size: $image_heap"
+    case "$arg" in
+      -v|--verbose)
+        verbose=yes
+        ;;
+      -V|--version)
+        print_version_info
+        exit 0
+        ;;
+      --show)
+        verbose=yes
+        show=yes
+        ;;
+      --help)
+        this_usage
+        exit 0
+        ;;
+      --help2)
+        display_help2=yes
+        ;;
+      --help-env)
+        this_usage_env
+        exit 0
+        ;;
+      --num-images=*)
+        num_images=`echo UhCaf$arg | sed -e 's/UhCaf--num-images=//g'`
+        if ! [[ "$num_images" =~ ^[0-9]+$ ]]; then
+          print_error "num-images specified is not valid"
         fi
-      fi
-      ;;
-    --)
-      option_parse=no
-      ;;
-    *)
-      if [ $option_parse = yes ]; then
-          program_cmd+="$arg "
-      fi
-      ;;
-  esac
+        ;;
+      -n|-np)
+        # next arg should be number of images
+        process_num_images=yes
+        ;;
+      --trace=*)
+        levels=`echo UhCaf$arg | sed -e 's/UhCaf--trace=//g'`
+        levels=`echo $levels | tr '[:lower:]' '[:upper:]'`
+        set_env UHCAF_TRACE $levels
+        if [ "${traces_enabled}" = "no" ]; then
+          print_warning "Traces disabled in CAF runtime"
+        fi
+        ;;
+      --trace-file=*)
+        trace_file=`echo UhCaf$arg | sed -e 's/UhCaf--trace-file=//g'`
+        set_env UHCAF_TRACE_FILE $trace_file
+        if [ "${traces_enabled}" = "no" ]; then
+          print_warning "Traces disabled in CAF runtime"
+        fi
+        ;;
+      --image-heap=*)
+        image_heap=`echo UhCaf$arg | sed -e 's/UhCaf--image-heap=//g'`
+
+        if [[ ! $image_heap =~ ^[0-9]+$ ]]; then
+          if [[  $image_heap =~ ^[0-9]+[kK]$ ]]; then
+            image_heap=$((${image_heap%?}*1024))
+          elif [[ $image_heap =~ ^[0-9]+[mM]$ ]]; then
+            image_heap=$((${image_heap%?}*1024*1024))
+          elif [[ $image_heap =~ ^[0-9]+[gG]$ ]]; then
+            image_heap=$((${image_heap%?}*1024*1024*1024))
+          else
+            print_error "Invalid per-image heap size: $image_heap"
+          fi
+        fi
+        ;;
+      -*)
+        echo "" >&2
+        echo "   Unrecognized option: $arg" >&2
+        echo "" >&2
+        this_usage
+        exit 1
+        ;;
+      *)
+        if [ $option_parse = yes ]; then
+            program_cmd+="$arg "
+        fi
+        program_name_seen=yes
+        ;;
+    esac
+
+  else # $program_name = yes
+
+      case "$arg" in
+        --)
+          option_parse=no
+          ;;
+        *)
+          if [ $option_parse = yes ]; then
+              program_cmd+="$arg "
+          fi
+          ;;
+      esac
+
+  fi
 
   if [ $pass_arg = no ]; then
       unset all_args[$arg_num]
@@ -286,22 +361,24 @@ all_args=${all_args[@]}
 prog_name=`echo ${program_cmd%% *}`
 prog_args=`echo ${program_cmd#$prog_name}`
 if [ -z "$prog_name" ]; then
-    if [ $display_help = yes -o $display_help2 = yes ]; then
-        if [ $display_help = yes  ]; then
-            this_usage
-        fi
-        if [ $display_help2 = yes ]; then
+    if [ $display_help2 = yes ]; then
+        if [ -n "$LAUNCHER"  ]; then
+            print_warning "Guessing that the launcher is $LAUNCHER"
             launcher_usage
+        else
+            print_error "Don't know what launcher to use."
         fi
         exit 0
     fi
+    this_usage
+    exit 0
 fi
 
 ###########################################
 # determine which communication layer to use
 
 if [ -z "$prog_name" ]; then
-    echo "Need to specify the program you want to run."
+    echo "Need to specify the program you want to run." >&2
     this_usage_short
     exit 1
 fi
@@ -319,26 +396,30 @@ if [ $COMM_LAYER == gasnet ]; then
     | sed 's/OPENUH_GASNET_CONDUIT_IS_//'`
 
   if [ -z "$GASNET_CONDUIT" ]; then
-    print_error "Cannot determine which GASNet conduit to use"
+    print_error "Cannot determine which GASNet conduit ot use"
+  fi
+fi
+
+if [ $COMM_LAYER == armci ]; then
+  ARMCI_NETWORK=`nm -a $prog_name | grep OPENUH_ARMCI_NETWORK_IS | cut -d" " -f3 \
+    | sed 's/OPENUH_ARMCI_NETWORK_IS_//'`
+
+  if [ -z "$ARMCI_NETWORK" ]; then
+    print_error "Cannot determine which ARMCI network to use"
   fi
 fi
 
 ###########################################
 # display help menu and exit, if necessary
-if [ $display_help = yes -o $display_help2 = yes ]; then
-    if [ $display_help = yes  ]; then
-        this_usage
+if [ $display_help2 = yes ]; then
+    if [ "$GASNET_CONDUIT" = "smp" ]; then
+        # no launcher used for GASNet's SMP conduit
+        unset LAUNCHER
     fi
-    if [ $display_help2 = yes ]; then
-        if [ "$GASNET_CONDUIT" = "smp" ]; then
-            # no launcher used for GASNet's SMP conduit
-            unset LAUNCHER
-        fi
-        launcher_usage
-    fi
-
+    launcher_usage
     exit 0
 fi
+
 
 ###########################################
 # set heap size in environment
@@ -388,28 +469,36 @@ fi
 
 ###########################################
 # set launcher information
-LAUNCHER_OPTS+=" $all_args"
+LAUNCHER_OPTS+=$all_args
+
+COMM_NETWORK=""
 
 ###########################################
-# Set environment for GASNET if used
+# Set environment for GASNET/ARMCI
 if [ $COMM_LAYER == gasnet ]; then
   # enable packing of non-contiguous put/get
   set_env GASNET_VIS_AMPIPE 1
 
   image_heap=$UHCAF_IMAGE_HEAP_SIZE
   if [ $image_heap -gt 2000000000 ]; then
-    gasnet_max_size="$(($image_heap/1000000000))G"
+    # Assume the GASNET segment should be in page-size (4K) multiples. Also,
+    # GASNet looks to reserve 2MB for something, so reserve space for that
+    # as well.
+    gasnet_max_size=$((($image_heap/4096+1)*4096 + 2*1024*1024))
     set_env GASNET_MAX_SEGSIZE $gasnet_max_size
   fi
-
+  COMM_NETWORK=$GASNET_CONDUIT
+elif [ $COMM_LAYER == armci ]; then
+  COMM_NETWORK=$ARMCI_NETWORK
 fi
+
 
 if [ "$GASNET_CONDUIT" = "smp" ]; then
   set_env GASNET_PSHM_NODES $num_images
   command="$program_cmd"  # just throw away $all_args?
 else
 
-  if [ ! -f `which $LAUNCHER` ]; then
+  if [ -z "`which $LAUNCHER 2> /dev/null`" ]; then
     print_error "Could not locate a launcher program. Specify with LAUNCHER variable"
   fi
 
@@ -419,7 +508,9 @@ else
 
   if [ \( $launcher_name = mpirun -o $launcher_name = mpiexec \) ]; then
     if [ $num_images -gt 1 ]; then
-      LAUNCHER_OPTS+=" -n $num_images"
+      LAUNCHER_OPTS=" -n $num_images $LAUNCHER_OPTS"
+    else
+      LAUNCHER_OPTS=" -n 1 $LAUNCHER_OPTS"
     fi
   fi
 
@@ -440,12 +531,18 @@ fi
 ENVIRONMENT+="-----------------------\n"
 case $verbose in
   yes)
-    echo "$this environment:"
-    echo -e $ENVIRONMENT
-    echo
-    echo "$this:"
-    echo "  $command"
-    echo
+    layer=`echo $COMM_LAYER | tr '[:lower:]' '[:upper:]'`
+    network=`echo $COMM_NETWORK | tr '[:upper:]' '[:lower:]'`
+    echo "" >&2
+    echo "program: $prog_name" >&2
+    echo "layer: $layer" >&2
+    echo "network: $network" >&2
+    echo "" >&2
+    echo "$this environment:" >&2
+    echo -e "$ENVIRONMENT" >&2
+    echo "" >&2
+    echo "command: $command" >&2
+    echo "" >&2
     ;;
   *)
     ;;
diff --git a/osprey/scripts/uhcaf.in b/osprey/scripts/uhcaf.in
--- a/osprey/scripts/uhcaf.in
+++ b/osprey/scripts/uhcaf.in
@@ -37,9 +37,9 @@ else
   tracing_enabled=no
 fi
 
-ARMCI_HOME=@ARMCI_HOME@
 GASNET_HOME=@GASNET_HOME@
 GASNET_CONDUIT=`echo "@GASNET_CONDUITS@" | cut -d" " -f1`
+ARMCI_HOME=@ARMCI_HOME@
 COMM_LAYER=@DEFAULT_COMM@
 CC=uhcc
 FC=uhf90
@@ -78,20 +78,25 @@ Where options are
   --keep, -k        Keep any temporary files in current directory
 
 Environment Variables:
+   MPI_LIB          Path to MPI libs is generally required. Should be
+                    compatible with GASNet or ARMCI installation being used.
+                        Currently: $MPI_LIB
 
-   ARMCI_NETWORK    Specifies network layer for ARMCI installation. See ARMCI documentation.
+   MPI_LD_LIBS      Explicitly specify MPI libs to link in.
+                        Currently: $MPI_LD_LIBS
 
-   MSG_COMMS        Messaging library used by ARMCI. Default is MPI.
-
-   TARGET           Target for the ARMCI installation. Defaults to LINUX64.
+   ARMCI specific environment variables:
 
    ARMCI_LIB        Path containing ARMCI lib (e.g. libarmci.a), if necessary.
-                        Typically: \$ARMCI_HOME/lib/\$TARGET
+                        Currently: $ARMCI_LIB
 
-   MPI_LIB          Path to MPI lib, if necessary.
+   ARMCI_NETWORK    Specifies network layer for ARMCI installation. See ARMCI
+                    documentation.
+                        Currently: $ARMCI_NETWORK
 
-   LIBMPI           Explicitly specify MPI libs to link in.
-                         Default is: -L\$MPI_LIB -lmpi
+   TARGET           Target for the ARMCI installation. Defaults to LINUX64.
+                        Currently: $TARGET
+
 
 _EOT_
 
@@ -125,13 +130,13 @@ set_env()
 
 print_error()
 {
-  echo "Error: $1" >&2
+  echo -e "Error: $*" >&2
   exit 1
 }
 
 print_warning()
 {
-  echo "Warning: $1" >&2
+  echo -e "Warning: $*" >&2
 }
 
 print_compile_link_info()
@@ -144,13 +149,13 @@ print_compile_link_info()
   if [ "$COMM_LAYER" == "gasnet" ]; then
       LAYER_INSTALLATION_PATH=$GASNET_HOME
       UHCAF_NETWORK=$GASNET_CONDUIT
-      if [ "$GASNET_CONDUIT" == "mpi" ]; then
+      if [ "$GASNET_CONDUIT" != "smp" ]; then
           MSG_LAYER=$MPI_LIB
       fi
   elif [ "$COMM_LAYER" == "armci" ]; then
       LAYER_INSTALLATION_PATH=$ARMCI_HOME
       UHCAF_NETWORK=$ARMCI_NETWORK
-      MSG_LAYER=$MSG_COMMS
+      MSG_LAYER=$MPI_LIB
   fi
 
   if [ -n "`$FC -V 2>&1 | grep -i \" --with-build-optimize=debug\"`" ]; then
@@ -180,7 +185,7 @@ print_compile_link_info()
         layer:           $COMM_LAYER ($LAYER_INSTALLATION_PATH)
         tracing:         $tracing_enabled
         network:         $UHCAF_NETWORK
-        messaging:       $MSG_LAYER
+        2-sided msg:     $MSG_LAYER
   ---------------------------------------------------------------------------
 _EOT_
 
@@ -250,13 +255,9 @@ for arg in "$@" ;  do
           ;;
         -h|--help)
           uhcaf_usage
-          pass_arg=no
-          link='n'
           ;;
         -H|--help2)
           uhf90_usage
-          pass_arg=no
-          link='n'
           ;;
         -help|-help:*)
           link='n'
@@ -288,7 +289,9 @@ for arg in "$@" ;  do
         --layer=*)
           val=`echo UhCaf$arg | sed -e 's/UhCaf--layer=//g'`
           layer=`echo $val | tr '[:upper:]' '[:lower:]'`
-          if [ $layer == armci ]; then
+          if [ -z "$layer" ]; then
+            print_error "layer needs to be specified with --layer"
+          elif [ $layer == armci ]; then
             COMM_LAYER=armci
           elif [[ $layer == gasnet-* ]]; then
             GASNET_CONDUIT=`echo $layer | sed 's/gasnet-//'`
@@ -352,6 +355,7 @@ elif [ $COMM_LAYER == armci -a -z "$ARMCI_HOME" ]; then
 fi
 
 
+
 if [ $COMM_LAYER == gasnet ]; then
 
   if [ -z "$GASNET_CONDUIT" ]; then
@@ -359,34 +363,77 @@ if [ $COMM_LAYER == gasnet ]; then
   fi
 
   if [ "$keep" == "y" ]; then
-    temp_name=`$mktemp_cmd`
-    mv $temp_name $temp_name.mak
-    echo -e "uhcaf-rule:\n\t@echo \$(GASNET_LIBS)"  \
-     | cat ${GASNET_HOME}/include/$GASNET_CONDUIT-conduit/$GASNET_CONDUIT-par.mak - \
-     > $temp_name.mak
-    COMM_LIBS=`make uhcaf-rule --no-print-directory -sf $temp_name.mak`
-  else
-    get_libs="echo -e \"uhcaf-rule:\n\t@echo \\\$(GASNET_LIBS)\"  \
-        | cat ${GASNET_HOME}/include/$GASNET_CONDUIT-conduit/$GASNET_CONDUIT-par.mak -  \
-        | make uhcaf-rule --no-print-directory -sf -"
-    COMM_LIBS=`eval $get_libs`
+      temp_name=`$mktemp_cmd`
+      mv $temp_name $temp_name.mak
+      echo -e "uhcaf-rule-mpi-linker:\n\t@echo \$(GASNET_LD)\n\n"  \
+      | cat ${GASNET_HOME}/include/$GASNET_CONDUIT-conduit/$GASNET_CONDUIT-par.mak - \
+      > $temp_name.mak
+      echo -e "uhcaf-rule-gasnet-libs:\n\t@echo \$(GASNET_LIBS)" >> $temp_name.mak
   fi
 
+  get_libs="echo -e \"uhcaf-rule:\n\t@echo \\\$(GASNET_LIBS)\"  \
+  | cat ${GASNET_HOME}/include/$GASNET_CONDUIT-conduit/$GASNET_CONDUIT-par.mak -  \
+  | make uhcaf-rule --no-print-directory -sf -"
+  COMM_LIBS=`eval $get_libs`
+
+
   if [ $GASNET_CONDUIT != smp ]; then
-    # need to link in MPI libs as well. If LIBMPI isn't defined, then
-    # just use -L${MPI_LIB} -lmpi
-    if [ -z "$LIBMPI" ] ; then
-      if [ -z "$MPI_LIB" ]; then
-        print_error "MPI_LIB needs to be set"
-      elif [ ! -d "$MPI_LIB" ]; then
-        print_error "MPI_LIB needs to be set to valid path. Currently: $MPI_LIB"
-      fi
-      LIBMPI="-L${MPI_LIB} -lmpi"
+
+    ##############################################################
+    # Try to figure out appropriate MPI_LIB and MPI_LD_LIBS from
+    # GASNet makefiles.
+    get_ld="echo -e \"uhcaf-rule:\n\t@echo \\\$(GASNET_LD)\"  \
+    | cat ${GASNET_HOME}/include/$GASNET_CONDUIT-conduit/$GASNET_CONDUIT-par.mak -  \
+    | make uhcaf-rule --no-print-directory -sf -"
+    mpi_ld=`eval $get_ld`
+    gasnet_mpi_lib=${mpi_ld%/bin*}/lib
+    if [ -z "$MPI_LIB" ]; then
+        MPI_LIB=$gasnet_mpi_lib
+        if [ ! -d "$MPI_LIB" ]; then
+            print_error "MPI_LIB needs to be set"
+        fi
+    elif [ -d "$gasnet_mpi_lib" -a -d "$MPI_LIB" ]; then
+        # check if they aren't the same
+        n1=`stat -c "%d%i" $gasnet_mpi_lib`
+        n2=`stat -c "%d%i" $MPI_LIB`
+        if [ "$n1" != "$n2" ]; then
+            warning_msg="It is recommended that MPI_LIB not point to a different"
+            warning_msg+=" installation than what GASNet was \nbuilt with."
+            warning_msg+=" Consider setting MPI_LIB=$gasnet_mpi_lib instead."
+            print_warning $warning_msg
+        fi
+    elif [ ! -d "$MPI_LIB" ]; then
+        print_warning "MPI_LIB not set to valid path. Using $gasnet_mpi_lib instead"
+        MPI_LIB=$gasnet_mpi_lib
     fi
-    COMM_LIBS="$COMM_LIBS -Wl,-rpath,$MPI_LIB $LIBMPI"
+
+    if [ -z "$MPI_LD_LIBS" ]; then
+        # MPI lib path was given, but can we figure out the necessary linker
+        # args?
+        if [ ! -f $MPI_LIB/../bin/mpicc ]; then
+            print_error "Can't determine what to link in from $MPI_LIB"
+        fi
+
+        mpi_ld=$MPI_LIB/../bin/mpicc
+
+        # does -showme:link work ?
+        MPI_LD_LIBS=`eval $mpi_ld -showme:link 2> /dev/null`
+        if [ "$?" != "0" ]; then
+            # does -link-info work?
+            ld_opt=`eval $mpi_ld -link-info 2> /dev/null`
+            if [ "$?" != "0" ]; then
+                print_error "MPI_LD_LIBS needs to be set"
+            fi
+            MPI_LD_LIBS=${ld_opt#*-L* }
+        fi
+        MPI_LD_LIBS="-L$MPI_LIB $MPI_LD_LIBS"
+    fi
+
+    # need to link in MPI libs as well.
+    COMM_LIBS="$COMM_LIBS -Wl,-rpath,$MPI_LIB $MPI_LD_LIBS"
 
     add_to_env_list "MPI_LIB"
-    add_to_env_list "LIBMPI"
+    add_to_env_list "MPI_LD_LIBS"
 
     if [ $GASNET_CONDUIT == udp ]; then
       CAF_FLAGS+=" -link-gcpp"  # use g++ for link if layer is gasnet-udp
@@ -397,11 +444,7 @@ if [ $COMM_LAYER == gasnet ]; then
 
 elif [ $COMM_LAYER == armci ]; then
 
-  if [ -z "$MSG_COMMS" -o "$MSG_COMMS" = "mpi" ]; then
-    set_env MSG_COMMS "MPI"
-  else
-    add_to_env_list "MSG_COMMS"
-  fi
+  set_env MSG_COMMS "MPI"
 
   if [ -z "$ARMCI_NETWORK" ]; then
     print_warning \
@@ -417,8 +460,16 @@ elif [ $COMM_LAYER == armci ]; then
     add_to_env_list "TARGET"
   fi
 
-  if [ $MSG_COMMS = MPI -a ! -d "$MPI_LIB" ]; then
-    print_error "MPI_LIB needs to be set to valid path. Currently: $MPI_LIB"
+  if [ ! -d "$MPI_LIB" ]; then
+    # check if mpicc exists in the path. If so, set MPI_LIB accordingly.
+    mpi_ld_path=`which mpicc 2> /dev/null`
+    if [ -f "$mpi_ld_path" ]; then
+        set_env MPI_LIB `dirname $mpi_ld_path`/../lib
+    else
+        print_error "MPI_LIB needs to be set to valid path."
+    fi
+  else
+    add_to_env_list "MPI_LIB"
   fi
 
   get_libs="echo -e \"uhcaf-rule:\n\t@echo -larmci \\\$(MP_LIBS) \\\$(COMM_LIBS)\" \
@@ -426,9 +477,7 @@ elif [ $COMM_LAYER == armci ]; then
         | make uhcaf-rule --no-print-directory -sf -"
 
   COMM_LIBS=`eval $get_libs`
-  if [ $MSG_COMMS = MPI ]; then
-    COMM_LIBS+=" -Wl,-rpath,$MPI_LIB "
-  fi
+  COMM_LIBS+=" -Wl,-rpath,$MPI_LIB "
 
   # find location of libarmci.a
   if [ -z "$ARMCI_LIB" ] ; then
@@ -440,7 +489,6 @@ elif [ $COMM_LAYER == armci ]; then
 
   COMM_LIBS="-lcaf-armci -L$ARMCI_LIB $COMM_LIBS"
 
-  add_to_env_list "MPI_LIB"
   add_to_env_list "ARMCI_LIB"
 
 fi
@@ -556,7 +604,8 @@ else
       # add some symbols into executable for cafrun script to check
       link_instructions=`$mktemp_cmd`
       symbol_defs="int OPENUH_COMM_LAYER_IS_$OPENUH_COMM_LAYER; \
-                  int OPENUH_GASNET_CONDUIT_IS_$GASNET_CONDUIT;"
+                  int OPENUH_GASNET_CONDUIT_IS_$GASNET_CONDUIT; \
+                  int OPENUH_ARMCI_NETWORK_IS_$ARMCI_NETWORK;"
 
       rm -f $link_instructions
       echo $symbol_defs | $CC -c -x c -o $link_instructions.o -
