[CAF] Misc. improvements/fixes to CAF implementation
Several improvements/fixes were made in CAF implementation, in particular to
improve the existing support for non-blocking communication and the logic for
when/how to create communication buffers.

* We add an environment variable, UHCAF_NB_XFER_LIMIT, to control the number
  of outstanding non-blocking PUT or GET calls that are allowed for a given
  image. By default, its being set to 16. We found that allow too many PUT or
  GET calls to accumulate can really slow down the underlying library (be it
  GASNet or ARMCI), so this provide a configurable way of throttling that.

* An LCB transfer was sometimes unnecessarily used when the root of the RHS tree
  was OPR_CVTL, which should now be fixed.  Also, the algorithm for statically
  detecting if an array section access is contiguous was flawed. It always
  returned false if the lower and upper bounds weren't constant, but for the
  case of an access like X(l:u) we know this is a contiguous access. This has
  been fixed.

* Fix Coarray_Prelower logic for creating LCB on coarray write

* Fix inter-image assignment of single value to array section

  A bug was introduced in 3.0.27 where inter-image assignment statements of a
  single value to an array section was not working. The following statements
  were broken:

  a(:)[i] = b(1)
  a(:)[i] = d
  b(:) = a(1)[i]
  b(:) = d[i]

  This was fixed by correcting the logic used to determine whether an LCB
  should be created for a found co-indexed term in the IR. Additionally, the
  change handles statements like the following more efficiently so that bulk
  transfers are generated.

  x(z(:)) = y(:)[i]
  y(:)[i] = x(z(:))

* The defer_sync directive was not being applied properly to statements
  containing function calls, like:

    x(:) = y(:)[num_images()]

  This is now corrected.  Also, we now use integer type instead of pointer
  type for caf_sync_handle

* Print more useful message when cafrun can't find executable to run.

* GASNet buffering optimization for nbread.  It is observed that when doing an
  nbread where the local destination is not in the shared memory segment, there
  is a significant overhead (apparently due to GASNet having to register/pin the
  destination buffer). This instead will allocate a buffer from the asymmetric
  heap in the shared memory segment to use as the destination buffer. Upon
  syncing on the handle, the data will be copied from this buffer to the actual
  destination.

* A new routine is added for asymmetric memory allocation which will return NULL
  if there wasn't sufficient space. This is now used for allocation of LCB and
  for the GASNet nbread local buffer.

* Fix setting of final_dest for nbread. The field handle_node->final_dest
  should only be set if a temporary local buffer is allocated from asymmetric
  shared memory heap for the purposes of this nbread transfer.

Contributor: Deepak

git-svn-id: https://svn.open64.net/svnroot/open64/branches/OpenUH@4061 ead328b1-e903-0410-a19d-eacee4b031f6

diff --git a/osprey/scripts/cafrun.in b/osprey/scripts/cafrun.in
--- a/osprey/scripts/cafrun.in
+++ b/osprey/scripts/cafrun.in
@@ -104,8 +104,12 @@ Environment Variables:
                       Set to 1 to enable getcache runtime optimization.
 
    UHCAF_GETCACHE_LINE_SIZE
-                      Spefies the size (in bytes) of the cache line used by
+                      Specifies the size (in bytes) of the cache line used by
                       getcache optimizer. By default it is 64KB.
+
+   UHCAF_NB_XFER_LIMIT
+                      Specifies the maximum number of outstanding non-blocking
+                      PUT or GET transfers. By default it is 16.
 
 _EOT_
 }
@@ -374,6 +378,10 @@ fi
 
 if [ -z "$prog_name" ]; then
     echo "Need to specify the program you want to run." >&2
+    this_usage_short
+    exit 1
+elif [ ! -f "$prog_name" ]; then
+    echo "cafrun was unable find the executable $prog_name." >&2
     this_usage_short
     exit 1
 fi
